### ISSUE TITLE
Use dependabot or another method to keep dependencies up to date

### ISSUE THREAD

**Issue by bertybuttface** [waylaidwanderer/node-chatgpt-api#1]
There are lots of breaking changes with the API necessitating fast paced releases upstream. Some sort of automation is required to keep pace with them and keep this package usable.

Dependabot only updates once a day so is quite slow, there must be a better method, do you know of one?

**Comment by waylaidwanderer** [comment]
Not sure what you're talking about. `chatgpt-api` has been working well for me without any changes needed in the past few weeks.

**Comment by waylaidwanderer** [comment]
Not sure if something like Watchtower can be added via PR, but you're welcome to make one if it is.
I wouldn't want to update anything other than `patch` versions automatically though. `minor` could introduce breaking changes.

**Comment by bertybuttface** [comment]
You already use a caret here: https://github.com/waylaidwanderer/node-chatgpt-api/blob/6007969b44402bef8312e4c1561f80c5225112d3/package.json#L31

That means as currently set you would pull in both `path` and `minor` versions if I'm not mistaken.

**Comment by bertybuttface** [comment]
In that case `package-lock.json` is locking the `chatgpt-api` version to `3.3.11` which no longer works with ChatGPT itself. Seems like a good reason to use GitHub's built in dependabot support which would keep that up to date too.

**Comment by waylaidwanderer** [comment]
I'm using it right now, and it's working somehow. I see on their repo that users are reporting issues, so I guess I'll update it quickly anyway.

**Comment by davemcm2** [comment]
I just cloned this repo and tried to use it without much success, a simple message would work, but as soon as you tried to add conversation id or parent message id it was getting 404 errors and failing.

I ran 'npm update' after finding this thread and now all is working properly.

**Comment by waylaidwanderer** [comment]
> Was the session already logged in from before the updates?

@bertybuttface No, I tested it with a fresh session. Anyway, I'll merge a PR to resolve this soon.

**Comment by bertybuttface** [comment]
The comment above is almost certainly the issue, by working I thought you meant fully working.

Thanks for adding Dependabot.

**Comment by waylaidwanderer** [comment]
@bertybuttface No worries. Sorry about the delay, I wanted to run some tests first to make sure the new version was working as expected.

**Comment by bertybuttface** [comment]
> someone tell me wtf this guy is going on about 

https://discord.com/channels/1051681201951342653/1051681202626642003/1062915766829187193

on Discord is a bit much when someone is trying to provide helpful (and correct) feedback.

**Comment by waylaidwanderer** [comment]
@bertybuttface I see you deleted your comment, but I'll reply to it anyway.

I think you misunderstood my intentions on Discord - I was actually kind of confused about what you were asking initially and was asking for help. I had to reread what you wrote several times before I understood that you were asking about implementing some automated way to keep up with updates to the `chatgpt` module.

**Comment by bertybuttface** [comment]
Asking for clarification would have been preferable to asking a group:

"someone tell me wtf this guy is going on about".

**Comment by waylaidwanderer** [comment]
I apologize if my previous message came across as rude or dismissive. I understand now that asking for clarification would have been a more appropriate way to handle the situation. I appreciate the time and effort you put into providing me with the correct information. I assure you that I will do better in the future and communicate more effectively. Thank you for your patience and understanding.

**Comment by bertybuttface** [comment]
Thanks I appreciate you saying that. Apologies for any lack of clarity or misunderstanding on my behalf.
