### ISSUE TITLE
I'm just running this demo, and it's giving me a timeout

### ISSUE THREAD

**Issue by eamd-wq** [waylaidwanderer/node-chatgpt-api#104]
![image](https://user-images.githubusercontent.com/58057732/220135276-c2ce64e8-456e-429f-8ded-5170b84b47f4.png)

**Comment by waylaidwanderer** [comment]
@eamd-wq Works fine for me. Could you make sure you're using a valid access token and that you're using the reverse proxy?

**Comment by eamd-wq** [comment]
> @eamd-wq对我来说很好用。您能确定您使用的是有效的访问令牌并且您使用的是反向代理吗？

I didn't change the url address in the file. I don't know if this is correct. I can confirm that my token is valid.
