### ISSUE TITLE
default model seems to be removed

### ISSUE THREAD

**Issue by yavuzakyuz** [waylaidwanderer/node-chatgpt-api#115]
The default model that comes with the package seems to be removed, the latest model leaked is also outputs 'That model does not exist' error. 

<img width="992" alt="Screenshot 2023-02-24 at 15 53 45" src="https://user-images.githubusercontent.com/56271907/221185277-eca2771a-2712-43e0-bf95-4d9799c72ffb.png">
<img width="783" alt="gppt23" src="https://user-images.githubusercontent.com/56271907/221185286-737869ea-bdd4-4b0d-a203-8b9dc677bb13.png">

**Comment by waylaidwanderer** [comment]
Apologies, the readme is a little unclear for this. OpenAI locked down those models, so you can only use a model like `text-davinci-003` with the API right now.

If you want to use chat.openai.com, you need to use `ChatGPTBrowserClient`.

**Comment by yavuzakyuz** [comment]
ah thanks for that, it works now
