### ISSUE TITLE
bingAIClient UnauthorizedRequest

### ISSUE THREAD

**Issue by waltcow** [waylaidwanderer/node-chatgpt-api#116]
document cookies is provided, but still return `UnauthorizedRequest`

```shell
node-chatgpt-api/demos/use-bing-client.js
{
  result: {
    value: 'UnauthorizedRequest',
    message: 'Sorry, you need to login first to access this service.'
  }
}
/node-chatgpt-api/src/BingAIClient.js:135
                throw new Error(`UnauthorizedRequest: ${createNewConversationResponse.result.message}`);
                      ^

Error: UnauthorizedRequest: Sorry, you need to login first to access this service.
    at BingAIClient.sendMessage (file:////node-chatgpt-api/src/BingAIClient.js:135:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///node-chatgpt-api/demos/use-bing-client.js:16:16

Node.js v18.14.2

Process finished with exit code 1


```

**Comment by waylaidwanderer** [comment]
Are you still on the waitlist?

**Comment by waltcow** [comment]
I can use it in my edge browser

Joel ***@***.***>于2023年2月25日 周六上午11:40写道：

**Comment by waylaidwanderer** [comment]
Show me your code for `use-bing-client.js`. I want to see how you set your cookie.

**Comment by waltcow** [comment]
I use the demo you provided. And grab the document.cookies from console in
bing page

Joel ***@***.***>于2023年2月25日 周六下午3:01写道：

**Comment by waylaidwanderer** [comment]
That's probably your issue. `document.cookie` will only have cookies accessible to the Javascript engine. Use devtools and copy it from a request's headers instead.

**Comment by waltcow** [comment]
Ok, thanks.i will try it later

Joel ***@***.***>于2023年2月25日 周六下午3:15写道：
