### ISSUE TITLE
model does not exist

### ISSUE THREAD

**Issue by kelchy** [waylaidwanderer/node-chatgpt-api#133]
anyone got non-proxy chatgpt client working?
i am getting "message: That model does not exist"
tried different models:
1. default
2. text-davinci-002-render-next
3. text-davinci-003
4. text-chat-davinci-002-20221122

all wont work

**Comment by waylaidwanderer** [comment]
Duplicate of #115

**Comment by waylaidwanderer** [comment]
@kelchy Make sure you set `text-davinci-003` (the only working model) under `modelOptions.model` for the `ChatGPTClient` options.
