### ISSUE TITLE
Bing new optionsSets

### ISSUE THREAD

**Issue by HalcyonAlcedo** [waylaidwanderer/node-chatgpt-api#135]
Bing has added new dialogue modes that allow AI to have different styles. These can be switched by modifying the optionsSets settings. Currently, harmonyv3 is the default balanced mode, h3imaginative is the creative mode. Perhaps it should allow customizing these attributes to achieve switching AI's style.

**Comment by waylaidwanderer** [comment]
Implemented in #141
