### ISSUE TITLE
New model 'gpt-3.5-turbo'

### ISSUE THREAD

**Issue by gitbute** [waylaidwanderer/node-chatgpt-api#136]
Hi there

There was a new model released (1/10th of the cost of davinci-003), but it only works with /v1/chat/completions.
We should patch it to work with this model.

https://techcrunch.com/2023/03/01/openai-launches-an-api-for-chatgpt-plus-dedicated-capacity-for-enterprise-customers/

Best regards

**Comment by waylaidwanderer** [comment]
Implemented in #137 and available in `@waylaidwanderer/chatgpt-api@1.22.0` :)
