### ISSUE TITLE
more than one account

### ISSUE THREAD

**Issue by logistic-people-deutschland** [waylaidwanderer/node-chatgpt-api#14]
I use 3 accounts

But now I have a problem when I start a conversation and I get a conversationId and I want to use it, I get an error "Conversation not found" because the system created the conversation with Accoount1 and is now using Account 3

what is the best way to solve this?

**Comment by waylaidwanderer** [comment]
No longer supported due to #15, which implements the (leaked) official ChatGPT model via OpenAI's API. Feel free to re-open if the model becomes disabled.
