### ISSUE TITLE
Can't see TOKEN usage

### ISSUE THREAD

**Issue by FraglyG** [waylaidwanderer/node-chatgpt-api#142]
I can't find a way to see how many tokens a response has used
was this implemented in this library?

**Comment by waylaidwanderer** [comment]
Token usage isn't provided if you are using stream mode. If you're not using stream mode, it'll be in the raw response. You can access the raw response by looking at the `details` property of the object returned by `sendMessage()`.
But if you are using stream mode, you must count it yourself.

**Comment by FraglyG** [comment]
Damn, alright thank you!
