### ISSUE TITLE
 Connect Timeout Error

### ISSUE THREAD

**Issue by soonxf** [waylaidwanderer/node-chatgpt-api#148]
### Excuse me, in this situation...

![image](https://github.com/soonxf/chatGPT-web/blob/main/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202023-03-03%20131621.png?raw=true)

![image](https://github.com/soonxf/chatGPT-web/blob/main/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202023-03-03%20131701.png?raw=true)

![image](https://github.com/soonxf/chatGPT-web/blob/main/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202023-03-03%20132701.png?raw=true)

**Comment by waylaidwanderer** [comment]
Duplicate of #144 probably

**Comment by soonxf** [comment]
### Proxy has been used

![image](https://github.com/soonxf/chatGPT-web/blob/main/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202023-03-03%20133848.png?raw=true)

![image](https://github.com/soonxf/chatGPT-web/blob/main/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202023-03-03%20134008.png?raw=true)
