### ISSUE TITLE
help me about use your code to call api.openai.com via proxy server (squid) ex: http://10.1.1.1:3218

### ISSUE THREAD

**Issue by nhannguyensy** [waylaidwanderer/node-chatgpt-api#149]
help me about use your code to call api.openai.com via proxy server (squid) ex: http://10.1.1.1:3218 ,Thanks !

**Comment by waylaidwanderer** [comment]
Proxy support has been added in https://github.com/waylaidwanderer/node-chatgpt-api/releases/tag/v1.26.0 which should fix this.
