### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by ganxiaozhe** [waylaidwanderer/node-chatgpt-api#153]
It appears that there is a memory leak issue in recent releases.

As the number of conversations increases, the memory usage of my Node.js process has grown from 90MB to 2GB.

I have conducted a swift review but have not identified any suspicious code. Has anyone encountered a similar issue?

Thank you.

**Comment by waylaidwanderer** [comment]
Which client are you using? What cache store are you using?

**Comment by ganxiaozhe** [comment]
I am utilizing the ChatGPTClient along with the default key-value storage.

Initially, I made some modifications to the logic of server.js and client, which resulted in a memory leak. I believed the issue was due to my changes. Therefore, in the latest version, I did not modify any files and only configured setting.js. Nevertheless, the memory leak issue still persists.

You may attempt to replicate the issue by running the server for an extended period or by conducting a few concurrent requests.
------- Original Message -------
2023年3月4日 星期六 下午 12:37，Joel ***@***.***> 来信：

**Comment by chiu0602** [comment]
I meet the same issue, I use default except `gpt-3.5-turbo` model.

**Comment by waylaidwanderer** [comment]
@ganxiaozhe Thanks. Can you try using a store like [`@keyv/redis`](https://www.npmjs.com/package/@keyv/redis) and see if the issue persists?

**Comment by ganxiaozhe** [comment]
@waylaidwanderer Understood. I'll try it later today.

**Comment by kevin-bk** [comment]
I got same issue

**Comment by kevin-bk** [comment]
> @ganxiaozhe Thanks. Can you try using a store like [`@keyv/redis`](https://www.npmjs.com/package/@keyv/redis) and see if the issue persists?

I have tried using keyv-redis, but the issue of RAM memory overflow still occurs, and so does the CPU.

**Comment by waylaidwanderer** [comment]
Can you guys upgrade to Node 19 and see if the issue persists? I've been testing the lib on that version and haven't encountered any problems.

**Comment by waylaidwanderer** [comment]
I've been drilling down into this on Node 16, but I can't reproduce it either.

If you guys can generate heap snapshots and anything else that would help debug this for me, that would be helpful.

**Comment by chiu0602** [comment]
it seems there is a infinite loop, after asking several questions, cpu loading go up straightly

**Comment by ganxiaozhe** [comment]
@waylaidwanderer I have been consistently utilizing Node 19. I surmise that the issue pertains to the ChatGPTClient.js file and is connected to the logic of the isChatGptModel variable, as it currently results in memory leaks only when this.modelOptions.model.startsWith('gpt-3.5-turbo')===true.

As of late, I have been preoccupied with other affairs and have not had the opportunity to conduct a more in-depth examination. I hope this information proves useful to you.

**Comment by waylaidwanderer** [comment]
I do heavily suspect it's related to the new tokenizer I'm using. Maybe it's not freeing the memory properly, or maybe it's something I'm doing.

Due to how the ChatGPT API formats prompts, the function that does the counting requires looping over the entire message array every time. So as each message is popped from the history, the entire array of messages in the conversation is looped over repeatedly. I think I can make the token counting code a bit uglier at the expense of optimizing the performance (i.e., each message's tokens are only counted once), so I'll make that change tomorrow and see if it helps.

**Comment by waylaidwanderer** [comment]
@ganxiaozhe thanks so much for your donation btw! 💖

**Comment by waylaidwanderer** [comment]
Hey guys, I've pushed an update to optimize the token counting algorithm, as previously mentioned. Please update to `@waylaidwanderer/chatgpt-api@1.25.7` and let me know if it improves the situation.

**Comment by ganxiaozhe** [comment]
> Hey guys, I've pushed an update to optimize the token counting algorithm, as previously mentioned. Please update to `@waylaidwanderer/chatgpt-api@1.25.7` and let me know if it improves the situation.

Thanks for the update. I have not observed any increase in memory usage after my continuous conversation, indicating that the issue appears to have been resolved. I will close this issue after it has remained stable for a day. 😊🎉

**Comment by kuangxiaoye** [comment]
> @waylaidwanderer/chatgpt-api@1.25.7

Hi is very glad that you are also using redis to store records. I encountered the following error after changing the code your way.


TypeError: Cannot read properties of undefined (reading 'options')
    at new KeyvRedis (/www/wwwroot/chatgpt-clone/api/node_modules/@keyv/redis/src/index.js:11:12)
    at askClient (/www/wwwroot/chatgpt-clone/api/app/clients/chatgpt-client.js:23:12)
    at async ask (/www/wwwroot/chatgpt-clone/api/server/routes/ask/askOpenAI.js:178:20)
    at async /www/wwwroot/chatgpt-clone/api/server/routes/ask/askOpenAI.js:89:10


Can you give me a little help? Thanks a lot
