### ISSUE TITLE
About some unexpected output when I using parentMessageId and conversationId on using api

### ISSUE THREAD

**Issue by eu09** [waylaidwanderer/node-chatgpt-api#160]
Im using the latest version of build and only using chatgpt , when u using a post without  parentMessageId and conversationId , it is normal , however when I add conversationId and parentMessageId , it flow out the error as below 
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "Unexpected string in JSON at position 42"
}

**Comment by waylaidwanderer** [comment]
@eu09 Set debug to true and post the output

**Comment by eu09** [comment]
I knew what is happening pls close . Thanks
