### ISSUE TITLE
Docker throws an error

### ISSUE THREAD

**Issue by xpediteur** [waylaidwanderer/node-chatgpt-api#166]
Hi, first of all, this is a really great app. Thanks for it. Running the app with "npm run server" works fine. But after running the container with "docker-compose up" and making a request the following error is thrown:
Error: Failed to send message. HTTP 404 - {
node-chatgpt-api-app-1 |   "error": {
node-chatgpt-api-app-1 |     "message": "This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?",

What's going wrong there? THX

**Comment by waylaidwanderer** [comment]
Sounds like your Docker image is out of date if you've previously created it using an old version. You can rebuild it with `docker-compose up --build`.

**Comment by xpediteur** [comment]
That was the problem. It was fixed with the --build parameter and runs fine now. Thanks very much.
