### ISSUE TITLE
I wanted to use web client but api server reported 'fetch failed'

### ISSUE THREAD

**Issue by Gyliiiiii** [waylaidwanderer/node-chatgpt-api#170]
<img width="1222" alt="image" src="https://user-images.githubusercontent.com/33806107/223317278-1e0e1e85-a9db-4539-a096-0e9220ff4523.png">
What should setting.js 'UseToClient' fill when using web-client?

**Comment by waylaidwanderer** [comment]
By web client you mean chat.openai.com? `apiOptions.clientToUse` should be `chatgpt-browser`, and you should make sure you've set `chatGptBrowserClient.reverseProxyUrl` to `https://chatgpt.duti.tech/api/conversation`.

**Comment by Gyliiiiii** [comment]
> I  mean  using your chatgpt-web-client  [waylaidwanderer/chatgpt-web-client](https://github.com/waylaidwanderer/chatgpt-web-client)

**Comment by waylaidwanderer** [comment]
Oh, well in that case, it will work with any of the `clientToUse` values that the API server supports.

**Comment by Gyliiiiii** [comment]
Ok, thank you. I have found the reason for the error. It is the wrong configuration in my setting.js file
