### ISSUE TITLE
why this prompt? tell it You are ChatGPT?

### ISSUE THREAD

**Issue by timestee** [waylaidwanderer/node-chatgpt-api#18]
https://github.com/waylaidwanderer/node-chatgpt-api/blob/d2cdb5831bdf8c653dec4d2600dceb333cfa2d30/src/ChatGPTClient.js#L137

**Comment by waylaidwanderer** [comment]
I explained it in the code comments. It's the same prompt that OpenAI gives to ChatGPT when you start a chat with it. It's just hidden to us.
