### ISSUE TITLE
Adapt to the parameters of discover-chat in edge111 version

### ISSUE THREAD

**Issue by OneSeven** [waylaidwanderer/node-chatgpt-api#189]
Hello, Microsoft released the edge111 version. In this version, new bing is integrated in the right sidebar, and I found that he seems to have more parameter options. Can you adapt the new parameters?

![20230315164459](https://user-images.githubusercontent.com/17974392/225254980-9894226e-b96c-445f-9e81-8324e1295d85.png)

**Comment by waylaidwanderer** [comment]
Feel free to submit a PR. I won't be focusing on the non-chat aspects of the Bing API.
