### ISSUE TITLE
404 Not Found 

### ISSUE THREAD

**Issue by danielmaela04** [waylaidwanderer/node-chatgpt-api#19]
file:///C:/Users/Daniel/Documents/2023/OpenAi/node_modules/@waylaidwanderer/chatgpt-api/src/ChatGPTClient.js:47
            const error = new Error(`Failed to send message. HTTP ${response.status} - ${body}`);
                          ^

Error: Failed to send message. HTTP 404 - {
    "error": {
        "message": "That model does not exist",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}

    at ChatGPTClient.getCompletion (file:///C:/Users/Daniel/Documents/2023/OpenAi/node_modules/@waylaidwanderer/chatgpt-api/src/ChatGPTClient.js:47:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChatGPTClient.sendMessage (file:///C:/Users/Daniel/Documents/2023/OpenAi/node_modules/@waylaidwanderer/chatgpt-api/src/ChatGPTClient.js:83:24)
    at async promptCompletion (file:///C:/Users/Daniel/Documents/2023/OpenAi/src/controllers/openAi/open.js:12:24) {
  status: 404,
  json: {
    error: {
      message: 'That model does not exist',
      type: 'invalid_request_error',
      param: null,
      code: null
    }
  }
}

**Comment by ERR0RPR0MPT** [comment]
Looks like OpenAI deprecated `text-chat-davinci-002-20230126`.
I tried `text-chat-davinci-002-20230130` which is not available for me.

**Comment by vaibhavard** [comment]
Try model: 'text-moderation-playground'.. Works for me as of 02-02-2023

**Comment by waylaidwanderer** [comment]
I updated the readme:

> Trying to use `text-chat-davinci-002-20230126` with the OpenAI API now returns a 404 error. Someone has already found the new model name, but they are refusing to share it. I will update this repository once I find the new model. If you have any leads, please open an issue or a pull request.

@vaibhavard `text-moderation-playground` isn't trained to be a chat model. You could drop in `text-davinci-003` as well but the results aren't as good as `text-chat-davinci` was.

**Comment by waylaidwanderer** [comment]
See https://github.com/transitive-bullshit/chatgpt-api/issues/292 for more discussion.

**Comment by iota-unum** [comment]
> I updated the readme:
> 
> > Trying to use `text-chat-davinci-002-20230126` with the OpenAI API now returns a 404 error. Someone has already found the new model name, but they are refusing to share it. I will update this repository once I find the new model. If you have any leads, please open an issue or a pull request.
> 
> @vaibhavard `text-moderation-playground` isn't trained to be a chat model. You could drop in `text-davinci-003` as well but the results aren't as good as `text-chat-davinci` was.

text-davinci-003 works very well, better than the previous model, but unfortunately openai charges for it (just tried myself).

**Comment by waylaidwanderer** [comment]
@iota-unum I've pushed 1.6.0, which supports other models better (namely replacing im_end and im_sep tokens with the endoftext token instead). From my testing, it works pretty well as a drop-in replacement as you said.

**Comment by allthingssecurity** [comment]
I got 404 and changed the model. Now I am getting 429. 
hatGPTError: ChatGPT error 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
I am using the Open AI API keys

**Comment by waylaidwanderer** [comment]
As I wrote in the readme, using this model costs money.

Check your usage and remaining credits: https://platform.openai.com/account/usage

**Comment by allthingssecurity** [comment]
Ok Thanks

**Comment by canfam** [comment]
@waylaidwanderer I have found a model that works, but I am not sure if it is the new one.
`text-chat-davinci-002-20221122`
It seems to work well for me 👍

**Comment by waylaidwanderer** [comment]
Thank you @canfam! I've pushed an update.
https://github.com/waylaidwanderer/node-chatgpt-api/releases/tag/v1.6.1

**Comment by timestee** [comment]
> 
Not as smart as ` text-chat-davinci-002-20230126`, quite far from~

**Comment by waylaidwanderer** [comment]
From our testing, it's identical in most ways to web ChatGPT's output but performs worse in some aspects like math, which is to be expected as it's an older model.
