### ISSUE TITLE
Updated moderation filter?

### ISSUE THREAD

**Issue by KevinKaiwenZheng** [waylaidwanderer/node-chatgpt-api#203]
I keep getting errors from the content moderation filter. It worked fine a few hours ago, but now I just get a bunch of errors triggering moderation filter. Is it my injected prompt had failed somehow or are people receiving this as well?

**Comment by tmkmch** [comment]
Yep. It seems, it's over.

**Comment by kamil-malinski** [comment]
it looks like Microsoft patched the "Jailbreak", you need to uncheck the Jailbreak checkbox and it will work again ("Sydney" is gone though)

**Comment by yuwangi** [comment]
I also met
