### ISSUE TITLE
-- GPT-4 API usable?

### ISSUE THREAD

**Issue by xpediteur** [waylaidwanderer/node-chatgpt-api#208]
Hi, can the GPT-4 API already be used with the current version? I got an error when I set the model to "GPT-4". THX

**Comment by yuwangi** [comment]
what  error?  please show it

**Comment by xpediteur** [comment]
the error:
```
error: {
      message: 'This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?',
      type: 'invalid_request_error',
      param: 'model',
      code: null
   }
```

**Comment by comienzo2093** [comment]
> the error:
> 
> ```
> error: {
>       message: 'This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?',
>       type: 'invalid_request_error',
>       param: 'model',
>       code: null
>    }
> ```
> 
> But, sorry, this was an old version 2 weeks ago!
> 
> I installed the new "version": "1.31.2", and get the error with using "GPT-4":
> 
> ```
> error: {
>       message: 'Incorrect API key provided: sk-u5yAB***************************************N6NQ. You can find your API key at https://platform.openai.com/account/api-keys.',
>       type: 'invalid_request_error',
>       param: null,
>       code: 'invalid_api_key'
>     }
> ```
> 
> I have set my current API-KEY correctly. With the old version and gpt-3.5-turbo the API-KEY works without problems.


Are you not in the gpt-4 queue and have you already licensed the gpt-4 api? I applied to use the api right after the release, but I haven't received a response yet.

**Comment by xpediteur** [comment]
I got this email from openAI:

**You're invited to use the OpenAI GPT-4 API!
--
You can now access GPT-4 models with 8K context via the existing OpenAI API.**

API should be open for me. But the current package is ready for GPT-4 or ?

**Comment by xpediteur** [comment]
I have now tried again and it works! Without stream, however, the response takes a very long time. Thanks for the support.

**Comment by waylaidwanderer** [comment]
Glad to hear your issue was resolved.

**Comment by puritynetwork** [comment]
> I have now tried again and it works! Without stream, however, the response takes a very long time. Thanks for the support.

Hi, I have the same problem as you, can you tell me how you solved it?

**Comment by xpediteur** [comment]
@puritynetwork 
I installed the new "version": "1.31.2", and after waiting a while, the API was unlocked by openAI and it works like charm. Or what problem do you have exactly?

**Comment by puritynetwork** [comment]
> @puritynetwork I installed the new "version": "1.31.2", and after waiting a while, the API was unlocked by openAI and it works like charm. Or what problem do you have exactly?


An error occurred. Please try again in a few moments.

Error message: Failed to send message. HTTP 404 - {
  "error": {
    "message": "This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?",
    "type": "invalid_request_error",
    "param": "model",
    "code": null
  }
}

**Comment by puritynetwork** [comment]
> @puritynetwork I installed the new "version": "1.31.2", and after waiting a while, the API was unlocked by openAI and it works like charm. Or what problem do you have exactly?

How to install new version

**Comment by xpediteur** [comment]
@puritynetwork 
npm install @waylaidwanderer/chatgpt-api@latest

**Comment by xpediteur** [comment]
@puritynetwork 
google or chatGPT should be your friend. The error is very unspecific.
