### ISSUE TITLE
api still not work 404 error，but cli could work- normally

### ISSUE THREAD

**Issue by zjrwtx** [waylaidwanderer/node-chatgpt-api#21]
![image](https://user-images.githubusercontent.com/86822589/216814112-64c721da-bac7-4786-ba7c-085bb3bd77df.png)
![image](https://user-images.githubusercontent.com/86822589/216814124-61942d90-a502-46a5-ae18-30a3a1373799.png)

**Comment by waylaidwanderer** [comment]
As per the readme, /conversation is a POST request.
