### ISSUE TITLE
Forbidden: Sorry, you are not allowed to access this service.

### ISSUE THREAD

**Issue by DrinklyDram** [waylaidwanderer/node-chatgpt-api#213]
i get this error when i try to run BingAIClient

file:///C:/Users/Drinkly/Desktop/ChatGPT_npm/src/BingAIClient.js:176
                    const e = new Error(createNewConversationResponse.result.message); // default e.name is 'Error'
                              ^

Forbidden: Sorry, you are not allowed to access this service.
    at BingAIClient.sendMessage (src/BingAIClient.js:176:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at demos/use-bing-client.js:20:16

bing ai works fine in browser

**Comment by DrinklyDram** [comment]
i somehow reloginned into another account which doesn't have access to the bing ai so i was getting the wrong _U cookie 😨

**Comment by veigamann** [comment]
I just came across this error. I was writing a side hustle/personal project that uses Bing (specifically Sydney) to chat with users on WhatsApp. I set it up to run in a group of friends, and we used it a lot in 2 days (maybe even too much). I started getting this error and thought it might be the cookie, but I cleared the cookies, generated a new one, and the error persists. I checked the Bing app on my phone and I can't use the chat. It tells me that I no longer have access to this service and asks me to check again in a few days. Could I have been temporarily/indefinitely banned for overuse?

I'll try with another account and come back here if I succeed.

**Comment by waylaidwanderer** [comment]
@veigamann Yes, I've had reports of that happening to others before. It's not specific to this package as some used the Python version, etc., probably due to overuse or problematic content.

From what I know, you'll get access back eventually.
