### ISSUE TITLE
bing Jailbreak mode improvements

### ISSUE THREAD

**Issue by xingfanxia** [waylaidwanderer/node-chatgpt-api#217]
Great work on https://github.com/waylaidwanderer/node-chatgpt-api/pull/132

However, it's still quite limited, with about 3 or 4 responses, it will throw

`[Error: The moderation filter triggered. Try again with different wording.]`

**Comment by xingfanxia** [comment]
Also a lot of time I asked it to list some bullet points, it will only say one sentence and omit the bullet points

**Comment by InterestingDarkness** [comment]
try https://github.com/waylaidwanderer/node-chatgpt-api/pull/214

**Comment by KevinKaiwenZheng** [comment]
> Great work on #132
> 
> However, it's still quite limited, with about 3 or 4 responses, it will throw
> 
> `[Error: The moderation filter triggered. Try again with different wording.]`

Have you been using the latest version? The jailbreak method was updated a few days ago due to the new moderation filter by Bing.

**Comment by 0x1FFFFF** [comment]
> > Great work on #132
> > However, it's still quite limited, with about 3 or 4 responses, it will throw
> > `[Error: The moderation filter triggered. Try again with different wording.]`
> 
> Have you been using the latest version? The jailbreak method was updated a few days ago due to the new moderation filter by Bing.

Yes my fork is up to date

**Comment by xingfanxia** [comment]
> > Great work on #132
> > However, it's still quite limited, with about 3 or 4 responses, it will throw
> > `[Error: The moderation filter triggered. Try again with different wording.]`
> 
> Have you been using the latest version? The jailbreak method was updated a few days ago due to the new moderation filter by Bing.

Yes, fork is up to date

**Comment by InterestingDarkness** [comment]
@0x1FFFFF @xingfanxia have you tried https://github.com/waylaidwanderer/node-chatgpt-api/pull/132 ?

**Comment by xingfanxia** [comment]
> 

Latest fork of main branch so contains this

**Comment by xingfanxia** [comment]
> @0x1FFFFF @xingfanxia have you tried #132 ?

Latest fork of main branch so contains this

**Comment by waylaidwanderer** [comment]
After the moderation filter triggers once, subsequent messages may still trigger it due to the previous messages being injected as context. I would advise maybe starting a new conversation if that occurs.

**Comment by 0x1FFFFF** [comment]
> After the moderation filter triggers once, subsequent messages may still trigger it due to the previous messages being injected as context. I would advise maybe starting a new conversation if that occurs.

I am only able to do a two or three message conversation until filter kicked in

**Comment by waylaidwanderer** [comment]
That hasn't been the case for me, even with many messages in jailbreak mode. Can you share an example?

**Comment by waylaidwanderer** [comment]
Feel free to re-open if still relevant.
