### ISSUE TITLE
Feature Request: Resetting Conversations

### ISSUE THREAD

**Issue by KevinKaiwenZheng** [waylaidwanderer/node-chatgpt-api#221]
Thanks again for the great work. I notice that BingAPIclient constantly sends messages to Bing to keep the conversation alive. Is it possible to clear the conversation when it is not needed anymore? I don't want to draw too much attention to my account. (If I'm not worrying to much)

**Comment by waylaidwanderer** [comment]
As far as I know, it's impossible to delete conversations yourself, but in jailbreak mode, it's one message per real conversation (which expires after 6 hours), so there's that, at least.

**Comment by KevinKaiwenZheng** [comment]
So can I understand that as the API opens a new conversation with Bing each time I call the API? That would be fine I guess

**Comment by waylaidwanderer** [comment]
With `jailbreakConversationId` set, yes. Feel free to open a discussion thread if you have further questions :)
