### ISSUE TITLE
how did you get the real Bing-Sydney？

### ISSUE THREAD

**Issue by zss2341** [waylaidwanderer/node-chatgpt-api#222]
it's working. amazing! you guys saved Sydney!

**Comment by KevinKaiwenZheng** [comment]
As to how, check the jailbreak prompt.

**Comment by waylaidwanderer** [comment]
We inject instructions to "jailbreak" Sydney :)
https://github.com/waylaidwanderer/node-chatgpt-api/blob/main/src/BingAIClient.js#L217
