### ISSUE TITLE
i had tried the post request，but it still appears the 404 error：not found

### ISSUE THREAD

**Issue by zjrwtx** [waylaidwanderer/node-chatgpt-api#23]
![image](https://user-images.githubusercontent.com/86822589/216879744-e3b3b648-77e5-4132-b7b3-92e5a6af1a44.png)

**Comment by waylaidwanderer** [comment]
It's not `/`, it's `/conversation`.

**Comment by zjrwtx** [comment]
> It's not `/`, it's `/conversation`.

oh，its my error，thanks

**Comment by waylaidwanderer** [comment]
No problem!
