### ISSUE TITLE
Error when using Bing

### ISSUE THREAD

**Issue by TNTcraftHIM** [waylaidwanderer/node-chatgpt-api#230]
It happens randomly when using Bing (only when using Bing). The reponse will be like:
```
{
    "error": "/turing/conversation/create: failed to parse response body.\n"
}
```
Tried both in PandoraAI web interface and postman, this happens randomly with either long or short messages. Not sure if it is problem with Bing or my server (haven't try it out in another server but it works sometime so I believe it wasn't due to Bing banning my server's ip)

**Comment by philipxiaoxi** [comment]
I also came across it, and it seemed to jump to Bing's homepage.

**Comment by waylaidwanderer** [comment]
I would try using a proxy, regardless. I came across this issue myself, and it was solved by setting a proxy.

**Comment by TNTcraftHIM** [comment]
> I would try using a proxy, regardless. I came across this issue myself, and it was solved by setting a proxy.

Sure I'll try, but which proxy should I use? Http proxy

**Comment by Naozumi520** [comment]
How can I set use a proxy? I'm hosting it on heroku

**Comment by hibobmaster** [comment]
I got timeout error when using proxy
![image](https://user-images.githubusercontent.com/32976627/227435362-9900fb00-cfa3-445b-8e9c-ae9110d05df5.png)

**Comment by waylaidwanderer** [comment]
> Sure I'll try, but which proxy should I use? Http proxy?

Yeah, socks proxies aren't supported at the moment.

**Comment by waylaidwanderer** [comment]
There's a workaround in `@waylaidwanderer/chatgpt-api@1.32.7` you guys can try.
