### ISSUE TITLE
Bug Fix:  Sorry, looks like your network settings are preventing access to this feature.

### ISSUE THREAD

**Issue by westwind027** [waylaidwanderer/node-chatgpt-api#232]
Today I found I couldn't use node-chatgpt-api anymore, the server response as:
![fc803bc8d7396aef1468bfbd434911e](https://user-images.githubusercontent.com/9116046/227440798-57b0ae92-0bed-4dd6-860d-e68d1f2b827d.png)
When I try to use browser to visit , the response as:
![e2a12826d054d9f92ed0d6795c74c3e](https://user-images.githubusercontent.com/9116046/227441026-004950ba-76b2-4b05-b64c-3ec56356f05a.png)
I found the solution:
![image](https://user-images.githubusercontent.com/9116046/227442193-8f31f49a-e704-4be4-bf49-36c682f7888a.png)
And modify the src/BingAIClient.js and recovery, hope it can help others 
![image](https://user-images.githubusercontent.com/9116046/227442356-7bf26c4d-155d-47ec-b46e-2f5f779862af.png)

**Comment by waylaidwanderer** [comment]
Thanks for reporting this! I'll close this in favor of #230, but I'll push out a patch immediately so you guys can test it.
