### ISSUE TITLE
Message will drop the html code when getting response

### ISSUE THREAD

**Issue by thunderning** [waylaidwanderer/node-chatgpt-api#233]
Message will drop the html code when getting response(e.g. <div class="..."/>)，I think it because project use "prompt" to send message . ChatGPT api docs said use "message" to chat and use "prompt" to completion, is it nessecary to use "prompt" now ?

**Comment by thunderning** [comment]
OK I can write html code by MarkDown gramma like ``` ```,maybe its not a bug. But I am still interested in 'prompt' and 'message'.Im appreciate If you can tell me the  reason.

**Comment by waylaidwanderer** [comment]
`prompt` is for `v1/completions` (e.g. text-davinci-003). `messages` is for `v1/chat/completions`

https://platform.openai.com/docs/api-reference/chat/create
