### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by zjrwtx** [waylaidwanderer/node-chatgpt-api#24]
<img width="960" alt="cdc34ecd2c7d5ae9a55183b68fb5ac1" src="https://user-images.githubusercontent.com/86822589/216907031-d6171aa3-72c3-4489-a8a0-d86f5b265696.png">
<img width="792" alt="7f5281d91a54863e2581e777601b068" src="https://user-images.githubusercontent.com/86822589/216907037-7b0e54a5-f438-4a1d-9245-e25ca6396beb.png">

**Comment by zjrwtx** [comment]
these are my front js code：
<img width="603" alt="e1697574ea272ef27b0e44c0a65bea9" src="https://user-images.githubusercontent.com/86822589/216908600-af11a926-3ed2-4013-b596-8aeccea753b3.png">

**Comment by waylaidwanderer** [comment]
Are you using https://github.com/fastify/fastify-cors?

Try
```JS
await server.register(cors, { 
  origin: '*',
  // OR
  origin: false,
});
```

If that works I'll update the server code to do that by default.

**Comment by waylaidwanderer** [comment]
Also, in your frontend code, maybe you should just use `ChatGPTClient` directly?

**Comment by zjrwtx** [comment]
> Are you using https://github.com/fastify/fastify-cors?
> 
> Try
> 
> ```js
> await server.register(cors, { 
>   origin: '*',
>   // OR
>   origin: false,
> });
> ```
> 
> If that works I'll update the server code to do that by default.

thanks，i solve it

**Comment by zjrwtx** [comment]
> Also, in your frontend code, maybe you should just use `ChatGPTClient` directly?

well，actual，i wanna deploy as a web app，it could be accessed in my mobile

**Comment by zjrwtx** [comment]
By the way, do you have a web frontend recommendation based on this api？

**Comment by waylaidwanderer** [comment]
> By the way, do you have a web frontend github project recommendation based on this api？

Not yet, but I plan on working on a simple one for this repo

**Comment by waylaidwanderer** [comment]
Closed with https://github.com/waylaidwanderer/node-chatgpt-api/releases/tag/v1.10.0
