### ISSUE TITLE
Putting Conversations Back

### ISSUE THREAD

**Issue by KevinKaiwenZheng** [waylaidwanderer/node-chatgpt-api#248]
I noticed that when I continued the conversation for roughly more than 3 turns, Sydney forgets the context of the discussion and begins with the introduction again. I suspect this is because the conversation is put in the `document summary`, resulting Sydney not recognizing it as previous conversation

**Comment by waylaidwanderer** [comment]
I can't say I'm experiencing the same thing, at least consistently. I've only had Sydney randomly say Hi once on the 3rd turn, but I've tried it several times and haven't reencountered it.

**Comment by KevinKaiwenZheng** [comment]
I have encountered several times. Maybe because I'm using a different system prompt. It may be more obvious and frequent if you give Sydney more rules and different identities. I'll leave this open to see if anyone else meet the same problem.

**Comment by InterestingDarkness** [comment]
try this: https://github.com/waylaidwanderer/node-chatgpt-api/commit/f685de75d84f86f38d608a0c939757a09d339bf6

**Comment by tmkmch** [comment]
The same problem. Sydney starts to repeat introduction of herself after few conversions and forgets the context of converstion. I'm also using more rules and different system prompt.

**Comment by getxd-dev** [comment]
> OK I've reproduced the issue. This may work [InterestingDarkness@bef4c97](https://github.com/InterestingDarkness/node-chatgpt-api/commit/bef4c9700eee6d4b8a5943bd2360c54de831dcdf)

Hello I tried this, I don't know if this is only on my side but it often cuts off the answer/response.

**Comment by InterestingDarkness** [comment]
> > OK I've reproduced the issue. This may work [InterestingDarkness@bef4c97](https://github.com/InterestingDarkness/node-chatgpt-api/commit/bef4c9700eee6d4b8a5943bd2360c54de831dcdf)
> 
> Hello I tried this, I don't know if this is only on my side but it often cuts off the answer/response.

Works well on my side. AI generated context will still be moderated.
