### ISSUE TITLE
出现Error: The moderation filter triggered. Try again with different wording.

### ISSUE THREAD

**Issue by 20000419** [waylaidwanderer/node-chatgpt-api#255]
如题。第一次对话都可以，但是在继续输入的时候无论输入什么都会显示
Error: The moderation filter triggered. Try again with different wording

**Comment by waylaidwanderer** [comment]
I've moved your issue to the correct repo.

**Comment by waylaidwanderer** [comment]
Should be fixed now with 1.33.1.
