### ISSUE TITLE
chatgpt-api command not work in my centos7,node16,but work normally in my windows

### ISSUE THREAD

**Issue by zjrwtx** [waylaidwanderer/node-chatgpt-api#26]
![image](https://user-images.githubusercontent.com/86822589/217138792-9107da7f-7e01-4a5d-952a-6148f1697044.png)

**Comment by waylaidwanderer** [comment]
![image](https://user-images.githubusercontent.com/2882110/217157303-8c6a10d3-bd6c-465e-b8d1-888c61c4d40b.png)

Looks like you need to update your Node.js.
