### ISSUE TITLE
Jailbroken Bing: Giving context breaks the jailbreak.

### ISSUE THREAD

**Issue by DaryeDev** [waylaidwanderer/node-chatgpt-api#260]
**Describe the bug**
Giving context to a Jailbroken Bing breaks the jailbreak and instead defaults to answering "Hello, I'm Bing", or something along those lines. Contextualization on normal Bing works as intended.

**To Reproduce**
1. Try the Context example on the `use-bing-client.js` demo on `demos/`, but jailbreak it.

**Expected behavior**
It had worked before, I did experiments with contextualization and it did work with Jailbroken Bing.

**Screenshots**
<img width="968" alt="image" src="https://user-images.githubusercontent.com/54469750/228902554-72c34f18-893a-4195-905a-974778f59612.png">

**Node.js version (please complete the following information):**
 - OS: MacOS ARM
 - Version v18.15.0

**Package version (please complete the following information):**
 - 1.33.0

**Comment by InterestingDarkness** [comment]
1.33.1 fixes jailbreak mode context input, try it

**Comment by DaryeDev** [comment]
> 1.33.1 fixes jailbreak mode context input, try it

It works, thanks.
