### ISSUE TITLE
It broken after update it.

### ISSUE THREAD

**Issue by SetoKaiba** [waylaidwanderer/node-chatgpt-api#265]
**Describe the bug**
I use the version contains no support to official model yet.
So I update it to the latest and use the latest settings template.
I run with problem now.
```
(node:623200) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/root/settings.js:1
export default {
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.14.1
```

**To Reproduce**
1. npm i -g @waylaidwanderer/chatgpt-api
2. chatgpt-cli

**Expected behavior**
It should work.

**Screenshots**

**Node.js version (please complete the following information):**
 - OS: Ubuntu
 - Version 18.14.1

**Package version (please complete the following information):**
 - 1.33.2

**Additional context**

**Comment by SetoKaiba** [comment]
I can run it with the project directly. But I can't run it with global modules.
```
npm install
npm run cli
```

**Comment by waylaidwanderer** [comment]
You can rename settings.js to settings.mjs instead, or change settings.js so that it uses `module.exports = { settings... }` instead of `export module` (as shown in the readme).

**Comment by SetoKaiba** [comment]
```
Error: the settings.js file does not exist.
```
Rename doesn't work. Modify to `module.exports = { settings... } works.

**Comment by waylaidwanderer** [comment]
Renaming would work if you set the path manually with `--settings=path/to/file.mjs` I think
