### ISSUE TITLE
I write a bat file to quickly open PandoraAI and api by BingGPT

### ISSUE THREAD

**Issue by Sissidark** [waylaidwanderer/node-chatgpt-api#274]
@ECHO OFF
rem Run the npm command in your api directory
start cmd.exe /k "cd /d X:\Your api floder location\\@waylaidwanderer\chatgpt-api && npm run server"

rem wait 2s,This command is not required
timeout /t 2 /nobreak >nul

rem Run the npm command in your PandoraAI directory
start cmd.exe /k "cd /d X:\Your PandoraAI floder location\PandoraAI && npm run dev"

rem open your browser link to your API_BASE_URL 
start http://localhost:XXXX/

**Comment by waylaidwanderer** [comment]
Thanks, this could come in useful. However, it is a duplicate issue of https://github.com/waylaidwanderer/PandoraAI/issues/52, so I'll close this one.

**Comment by lover-shadow** [comment]
这段命令看起来像AI自动生成的 。
bing ai 就是这么告诉我的 ^^Y

**Comment by Sissidark** [comment]
> 这段命令看起来像AI自动生成的 。 bing ai 就是这么告诉我的 ^^Y

是的，我也说了是通过bing🤣
