### ISSUE TITLE
Seems they patched something

### ISSUE THREAD

**Issue by asus12345AVAIALBALEELELEL** [waylaidwanderer/node-chatgpt-api#275]
`x-forwarded-for` doesn't work today, instead, it outputs this:
![image](https://user-images.githubusercontent.com/125299786/229926281-5c4a6d82-fd9b-4b6a-b4bf-79a738170177.png)
![image](https://user-images.githubusercontent.com/125299786/229924147-7b803bc0-adfc-4268-a48e-e9f7f5e2bbe3.png)

yet, it still persists..

**Comment by waylaidwanderer** [comment]
In your browser, can you send a message, click on "create" in Dev Tools (F12) > Network Requests, and check what the "Request URL" value is?
![image](https://user-images.githubusercontent.com/2882110/229927686-3d474946-8817-449e-9d44-2d4650c69ad9.png)

**Comment by asus12345AVAIALBALEELELEL** [comment]
![image](https://user-images.githubusercontent.com/125299786/229928734-5135f964-ce66-44f4-a7ed-1ae244530470.png)
the request URL is the same, also I'm using a browser VPN to access bing ai, else the "CHAT" tab won't show up.

However with `x-forwarded-for`, it didn't output this before, it only happens today.

**Comment by asus12345AVAIALBALEELELEL** [comment]
damn, well, thanks for letting me know
