### ISSUE TITLE
Allow passing per-message client options/params

### ISSUE THREAD

**Issue by z0lo13** [waylaidwanderer/node-chatgpt-api#28]
Ability to set OpenAI API key for server on the first request to it

**Comment by waylaidwanderer** [comment]
@z0lo13 could you explain your use-case for this?

**Comment by z0lo13** [comment]
It will open an ability to have multi users for apps/front without node.js support. It would be great if api key is saved on session. 

For now I accomplished the same thing with the client library which is ran on my express server. So I am not really sure if that will be useful for that.

Another use scenario is the ability to switch the open ai api key without editing or restarting the server.

Again, both of the above are perfectly achievable with a custom server like express and client library, however if you're to supporting the server portion, I suppose It could be useful.

**Comment by waylaidwanderer** [comment]
I want to allow setting model parameters on a per-message basis in the future. A configurable API key could be part of that as well.

**Comment by z0lo13** [comment]
@waylaidwanderer that would be great if you consider this in next updates

**Comment by waylaidwanderer** [comment]
Now available in https://github.com/waylaidwanderer/node-chatgpt-api/releases/tag/v1.28.0

**Comment by waylaidwanderer** [comment]
FYI @z0lo13, I won't support sessions for the API server, so you'll have to store the options some other way, such as in the browser's local storage. Alternatively, you can run your own server that uses the new feature.
