### ISSUE TITLE
Sydney sometimes keeps repeating information from previous answers even when I tell her not to.

### ISSUE THREAD

**Issue by Sissidark** [waylaidwanderer/node-chatgpt-api#289]
Sydney sometimes keeps repeating information from previous answers even when I tell her not to.
Is there any way to limit her? For example, add a line order in the prompt?

**Comment by ayxj0** [comment]
Yes, I have also encountered this problem. I am currently using version 1.33.3. I found that when I have more conversations with the AI, this issue becomes more likely to occur, and at the moment, I have no way to correct it.

**Comment by InterestingDarkness** [comment]
https://github.com/waylaidwanderer/node-chatgpt-api/pull/277
Maybe it's caused by this. I've tried "use empty string for real user message", but it caused the issue. That's why I gave up on this approach.

**Comment by iouzzrj** [comment]
I think I have this issue too. Sydney just start to repeat "Hi I am Sydney, your AI assistant" after several conversation. She ignore my reply and just repeat.

**Comment by Sissidark** [comment]
> #277 Maybe it's caused by this. I've tried "use empty string for real user message", but it caused the issue. That's why I gave up on this approach.

I downloaded the latest zip file to replace my old one, but the problem still persists, Sydney now doesn't repeat what he said before, but keeps repeating "hi, im Sydney..." as  she seems like to forget everything.

**Comment by ayxj0** [comment]
> > #277 Maybe it's caused by this. I've tried "use empty string for real user message", but it caused the issue. That's why I gave up on this approach.
> 
> I downloaded the latest zip file to replace my old one, but the problem still persists, Sydney now doesn't repeat what he said before, but keeps repeating "hi, im Sydney..." as she seems like to forget everything.
![1](https://user-images.githubusercontent.com/65698409/230719999-a21aa55c-9631-4771-ab04-63bca837cca3.png)

I just tried it, and it works much better after I updated to the latest version 1.34.0, are you sure you updated to version 1.34.0?

**Comment by InterestingDarkness** [comment]
You can try to downgrade to 1.33.3

**Comment by Sissidark** [comment]
> > > #277 Maybe it's caused by this. I've tried "use empty string for real user message", but it caused the issue. That's why I gave up on this approach.
> > 
> > 
> > I downloaded the latest zip file to replace my old one, but the problem still persists, Sydney now doesn't repeat what he said before, but keeps repeating "hi, im Sydney..." as she seems like to forget everything.
> > ![1](https://user-images.githubusercontent.com/65698409/230719999-a21aa55c-9631-4771-ab04-63bca837cca3.png)
> 
> I just tried it, and it works much better after I updated to the latest version 1.34.0, are you sure you updated to version 1.34.0?



> You can try to downgrade to 1.33.3

yes,I just downloaded it and replaced my old files. But it still has problems now:
![image](https://user-images.githubusercontent.com/92515662/230727407-170d4c77-efaf-4075-968e-26ed8e27319c.png)

**Comment by InterestingDarkness** [comment]
Downgrade to 1.33.3 and reset the conversation, see if the problem still occurs

**Comment by Sissidark** [comment]
> Downgrade to 1.33.3 and reset the conversation, see if the problem still occurs

I will try later,anyway thank you!

**Comment by Sissidark** [comment]
> Downgrade to 1.33.3 and reset the conversation, see if the problem still occurs

In fact before my update she just kept repeating what she said before, instead of being in a state of "amnesia" like this.

**Comment by ayxj0** [comment]
> 



> > Downgrade to 1.33.3 and reset the conversation, see if the problem still occurs
> 
> In fact before my update she just kept repeating what she said before, instead of being in a state of "amnesia" like this.
Really? Can you take a screenshot and show me your version number?

**Comment by ayxj0** [comment]
> > > > #277 Maybe it's caused by this. I've tried "use empty string for real user message", but it caused the issue. That's why I gave up on this approach.
> > > 
> > > 
> > > I downloaded the latest zip file to replace my old one, but the problem still persists, Sydney now doesn't repeat what he said before, but keeps repeating "hi, im Sydney..." as she seems like to forget everything.
> > > ![1](https://user-images.githubusercontent.com/65698409/230719999-a21aa55c-9631-4771-ab04-63bca837cca3.png)
> > 
> > 
> > I just tried it, and it works much better after I updated to the latest version 1.34.0, are you sure you updated to version 1.34.0?
> 
> > You can try to downgrade to 1.33.3
> 
> yes,I just downloaded it and replaced my old files. But it still has problems now: ![image](https://user-images.githubusercontent.com/92515662/230727407-170d4c77-efaf-4075-968e-26ed8e27319c.png)
Really? Can you take a screenshot and show me your version number?

**Comment by Sissidark** [comment]
> > > > > #277 Maybe it's caused by this. I've tried "use empty string for real user message", but it caused the issue. That's why I gave up on this approach.
> > > > 
> > > > 
> > > > I downloaded the latest zip file to replace my old one, but the problem still persists, Sydney now doesn't repeat what he said before, but keeps repeating "hi, im Sydney..." as she seems like to forget everything.
> > > > ![1](https://user-images.githubusercontent.com/65698409/230719999-a21aa55c-9631-4771-ab04-63bca837cca3.png)
> > > 
> > > 
> > > I just tried it, and it works much better after I updated to the latest version 1.34.0, are you sure you updated to version 1.34.0?
> > 
> > 
> > > You can try to downgrade to 1.33.3
> > 
> > 
> > yes,I just downloaded it and replaced my old files. But it still has problems now: ![image](https://user-images.githubusercontent.com/92515662/230727407-170d4c77-efaf-4075-968e-26ed8e27319c.png)
> > Really? Can you take a screenshot and show me your version number?

![image](https://user-images.githubusercontent.com/92515662/230727814-328df014-615a-45c0-a997-36033cb531d1.png)

**Comment by InterestingDarkness** [comment]
I see you paste some code in the input. Then you can try to change this line https://github.com/waylaidwanderer/node-chatgpt-api/blob/1462e9eb2deeb3a926a5245d61e4f12f0f67dcfa/src/BingAIClient.js#L333
to `text: message,` this will solve some problems
But in this way your input will trigger moderation so there's a trade-off

**Comment by ayxj0** [comment]
> > > > > > #277 Maybe it's caused by this. I've tried "use empty string for real user message", but it caused the issue. That's why I gave up on this approach.
> > > > > 
> > > > > 
> > > > > I downloaded the latest zip file to replace my old one, but the problem still persists, Sydney now doesn't repeat what he said before, but keeps repeating "hi, im Sydney..." as she seems like to forget everything.
> > > > > ![1](https://user-images.githubusercontent.com/65698409/230719999-a21aa55c-9631-4771-ab04-63bca837cca3.png)
> > > > 
> > > > 
> > > > I just tried it, and it works much better after I updated to the latest version 1.34.0, are you sure you updated to version 1.34.0?
> > > 
> > > 
> > > > You can try to downgrade to 1.33.3
> > > 
> > > 
> > > yes,I just downloaded it and replaced my old files. But it still has problems now: ![image](https://user-images.githubusercontent.com/92515662/230727407-170d4c77-efaf-4075-968e-26ed8e27319c.png)
> > > Really? Can you take a screenshot and show me your version number?
> 
> ![image](https://user-images.githubusercontent.com/92515662/230727814-328df014-615a-45c0-a997-36033cb531d1.png)
这真的很奇怪，我之前用的是1.33.3版本的，对话过多会有问题。但是当我升级到1.34.0后，使用非常顺畅，没有任何对话重复的问题。

**Comment by InterestingDarkness** [comment]
In 1.34.0, you can also change this line https://github.com/waylaidwanderer/node-chatgpt-api/blob/96db6e127d292d5deb34893582a8ab4004dea540/src/BingAIClient.js#L318
to `text: message,`

**Comment by Sissidark** [comment]
> I see you paste some code in the input. Then you can try to change this line
> 
> https://github.com/waylaidwanderer/node-chatgpt-api/blob/1462e9eb2deeb3a926a5245d61e4f12f0f67dcfa/src/BingAIClient.js#L333
> 
> 
> to this will solve some problems
> But in this way your input will trigger moderation so there's a trade-off`text: message,`

Yes, the version I was using before is the code like this, she keeps repeating the previous answer sometimes, but it won't temporarily reset like now.

**Comment by ayxj0** [comment]
> > I see you paste some code in the input. Then you can try to change this line
> > https://github.com/waylaidwanderer/node-chatgpt-api/blob/1462e9eb2deeb3a926a5245d61e4f12f0f67dcfa/src/BingAIClient.js#L333
> > 
> > to this will solve some problems
> > But in this way your input will trigger moderation so there's a trade-off`text: message,`
> 
> Yes, the version I was using before is the code like this, she keeps repeating the previous answer sometimes, but it won't temporarily reset like now.

我有个建议，你别直接覆盖旧版本，你可以尝试新建一个文件夹然后重新再装一次最新版本

**Comment by Sissidark** [comment]
> > > I see you paste some code in the input. Then you can try to change this line
> > > https://github.com/waylaidwanderer/node-chatgpt-api/blob/1462e9eb2deeb3a926a5245d61e4f12f0f67dcfa/src/BingAIClient.js#L333
> > > 
> > > to this will solve some problems
> > > But in this way your input will trigger moderation so there's a trade-off`text: message,`
> > 
> > 
> > Yes, the version I was using before is the code like this, she keeps repeating the previous answer sometimes, but it won't temporarily reset like now.
> 
> 我有个建议，你别直接覆盖旧版本，你可以尝试新建一个文件夹然后重新再装一次最新版本

You're right!I will try it.

**Comment by ayxj0** [comment]
> > > > I see you paste some code in the input. Then you can try to change this line
> > > > https://github.com/waylaidwanderer/node-chatgpt-api/blob/1462e9eb2deeb3a926a5245d61e4f12f0f67dcfa/src/BingAIClient.js#L333
> > > > 
> > > > to this will solve some problems
> > > > But in this way your input will trigger moderation so there's a trade-off`text: message,`
> > > 
> > > 
> > > Yes, the version I was using before is the code like this, she keeps repeating the previous answer sometimes, but it won't temporarily reset like now.
> > 
> > 
> > 我有个建议，你别直接覆盖旧版本，你可以尝试新建一个文件夹然后重新再装一次最新版本
> 
> You're right!I will try it.

你可以自查一下，我的最新文件的那条代码是这样的 text: jailbreakConversationId ? '' : message,  
你如果查不到这条代码，就说明你用的依旧是旧版本的文件，只是版本号升级了（真的只升级了版本号）

**Comment by Sissidark** [comment]
> > > > > I see you paste some code in the input. Then you can try to change this line
> > > > > https://github.com/waylaidwanderer/node-chatgpt-api/blob/1462e9eb2deeb3a926a5245d61e4f12f0f67dcfa/src/BingAIClient.js#L333
> > > > > 
> > > > > to this will solve some problems
> > > > > But in this way your input will trigger moderation so there's a trade-off`text: message,`
> > > > 
> > > > 
> > > > Yes, the version I was using before is the code like this, she keeps repeating the previous answer sometimes, but it won't temporarily reset like now.
> > > 
> > > 
> > > 我有个建议，你别直接覆盖旧版本，你可以尝试新建一个文件夹然后重新再装一次最新版本
> > 
> > 
> > You're right!I will try it.
> 
> 你可以自查一下，我的最新文件的那条代码是这样的 text: jailbreakConversationId ? '' : message, 你如果查不到这条代码，就说明你用的依旧是旧版本的文件，只是版本号升级了（真的只升级了版本号）

我检查了，最新版本的代码似乎是这样的：
```
text: jailbreakConversationId ? '\n\nAI:\n' : message,
```

**Comment by ayxj0** [comment]
> > > > > > I see you paste some code in the input. Then you can try to change this line
> > > > > > https://github.com/waylaidwanderer/node-chatgpt-api/blob/1462e9eb2deeb3a926a5245d61e4f12f0f67dcfa/src/BingAIClient.js#L333
> > > > > > 
> > > > > > to this will solve some problems
> > > > > > But in this way your input will trigger moderation so there's a trade-off`text: message,`
> > > > > 
> > > > > 
> > > > > Yes, the version I was using before is the code like this, she keeps repeating the previous answer sometimes, but it won't temporarily reset like now.
> > > > 
> > > > 
> > > > 我有个建议，你别直接覆盖旧版本，你可以尝试新建一个文件夹然后重新再装一次最新版本
> > > 
> > > 
> > > You're right!I will try it.
> > 
> > 
> > 你可以自查一下，我的最新文件的那条代码是这样的 text: jailbreakConversationId ? '' : message, 你如果查不到这条代码，就说明你用的依旧是旧版本的文件，只是版本号升级了（真的只升级了版本号）
> 
> 我检查了，最新版本的代码似乎是这样的：
> 
> ```
> text: jailbreakConversationId ? '\n\nAI:\n' : message,
> ```

不不不，这个版本我用过，这是旧代码，我用的时候有很明显的重复对话的bug。这真的是旧代码，我看到作者三天前就把这行代码改掉了

**Comment by Sissidark** [comment]
> > > > > > > I see you paste some code in the input. Then you can try to change this line
> > > > > > > https://github.com/waylaidwanderer/node-chatgpt-api/blob/1462e9eb2deeb3a926a5245d61e4f12f0f67dcfa/src/BingAIClient.js#L333
> > > > > > > 
> > > > > > > to this will solve some problems
> > > > > > > But in this way your input will trigger moderation so there's a trade-off`text: message,`
> > > > > > 
> > > > > > 
> > > > > > Yes, the version I was using before is the code like this, she keeps repeating the previous answer sometimes, but it won't temporarily reset like now.
> > > > > 
> > > > > 
> > > > > 我有个建议，你别直接覆盖旧版本，你可以尝试新建一个文件夹然后重新再装一次最新版本
> > > > 
> > > > 
> > > > You're right!I will try it.
> > > 
> > > 
> > > 你可以自查一下，我的最新文件的那条代码是这样的 text: jailbreakConversationId ? '' : message, 你如果查不到这条代码，就说明你用的依旧是旧版本的文件，只是版本号升级了（真的只升级了版本号）
> > 
> > 
> > 我检查了，最新版本的代码似乎是这样的：
> > ```
> > text: jailbreakConversationId ? '\n\nAI:\n' : message,
> > ```
> 
> 不不不，这个版本我用过，这是旧代码，我用的时候有很明显的重复对话的bug。这真的是旧代码，我看到作者三天前就把这行代码改掉了

刚刚覆盖错了文件，这个是正确的：
```
text: jailbreakConversationId ? '' : message,

**Comment by Sissidark** [comment]
> > > I see you paste some code in the input. Then you can try to change this line
> > > https://github.com/waylaidwanderer/node-chatgpt-api/blob/1462e9eb2deeb3a926a5245d61e4f12f0f67dcfa/src/BingAIClient.js#L333
> > > 
> > > to this will solve some problems
> > > But in this way your input will trigger moderation so there's a trade-off`text: message,`
> > 
> > 
> > Yes, the version I was using before is the code like this, she keeps repeating the previous answer sometimes, but it won't temporarily reset like now.
> 
> 我有个建议，你别直接覆盖旧版本，你可以尝试新建一个文件夹然后重新再装一次最新版本

好像好了，哥们你真的牛！看来每次更新都要重新部署，直接覆盖不太行，非常感谢！
It's working fine now, buddy you're really good! It seems that you need to install again after each update, and you cannot directly overwrite the file, thank you very much!

**Comment by ayxj0** [comment]
> > > > I see you paste some code in the input. Then you can try to change this line
> > > > https://github.com/waylaidwanderer/node-chatgpt-api/blob/1462e9eb2deeb3a926a5245d61e4f12f0f67dcfa/src/BingAIClient.js#L333
> > > > 
> > > > to this will solve some problems
> > > > But in this way your input will trigger moderation so there's a trade-off`text: message,`
> > > 
> > > 
> > > Yes, the version I was using before is the code like this, she keeps repeating the previous answer sometimes, but it won't temporarily reset like now.
> > 
> > 
> > 我有个建议，你别直接覆盖旧版本，你可以尝试新建一个文件夹然后重新再装一次最新版本
> 
> 好像好了，哥们你真的牛！看来每次更新都要重新部署，直接覆盖不太行，非常感谢！ It's working fine now, buddy you're really good! It seems that you need to install again after each update, and you cannot directly overwrite the file, thank you very much!

因为我也是经常遇到各种奇奇怪怪的问题啊哈哈

**Comment by Sissidark** [comment]
![image](https://user-images.githubusercontent.com/92515662/230878483-d2808c84-c789-4229-8c3d-9b54da2d8ca8.png)
![image](https://user-images.githubusercontent.com/92515662/230878491-94c6b84a-0bf6-4517-bd08-af348e1d4959.png)

![image](https://user-images.githubusercontent.com/92515662/230878437-c3961159-037c-409e-925e-f49e6d85ed84.png)

reinstall the project doesn't resolve this problem yet.

**Comment by ayxj0** [comment]
> ![image](https://user-images.githubusercontent.com/92515662/230878483-d2808c84-c789-4229-8c3d-9b54da2d8ca8.png) ![image](https://user-images.githubusercontent.com/92515662/230878491-94c6b84a-0bf6-4517-bd08-af348e1d4959.png)
> 
> ![image](https://user-images.githubusercontent.com/92515662/230878437-c3961159-037c-409e-925e-f49e6d85ed84.png)
> 
> reinstall the project doesn't resolve this problem yet.

一个对话不能太长，我测试过大概聊天超过4000个字左右就会出现遗忘现象，必须开启新的对话。

**Comment by ayxj0** [comment]
> ![image](https://user-images.githubusercontent.com/92515662/230878483-d2808c84-c789-4229-8c3d-9b54da2d8ca8.png) ![image](https://user-images.githubusercontent.com/92515662/230878491-94c6b84a-0bf6-4517-bd08-af348e1d4959.png)
> 
> ![image](https://user-images.githubusercontent.com/92515662/230878437-c3961159-037c-409e-925e-f49e6d85ed84.png)
> 
> reinstall the project doesn't resolve this problem yet.

需要注意的是，目前我个人认为没有办法修复这个问题。当时new bing刚开始公测的时候，是没有对话次数限制的，我发现官方的new bing对话次数长了也会出现遗忘现象，所以后来微软才会对new bing的对话次数进行限制。

**Comment by vuminhquang** [comment]
This bug might related to #354 , posted yesterday. This is because that BingAIClient keep create new session again and again.

**Comment by InterestingDarkness** [comment]
> This bug might related to #354 , posted yesterday. This is because that BingAIClient keep create new session again and again.

no, https://github.com/waylaidwanderer/node-chatgpt-api/pull/350 fixed it

**Comment by vuminhquang** [comment]
I applied 350 to my local, and see that it's not eliminate the root cause. 

And I got this error on the second message
![image](https://user-images.githubusercontent.com/20512463/236870686-06fd76c4-5760-4655-87bd-917cbf12ca88.png)

Beside, '' should be sent the first time.
![image](https://user-images.githubusercontent.com/20512463/236869603-6564bda5-dfec-4693-91b0-54f180b1544a.png)
