### ISSUE TITLE
The URL cannot be opened and read accurately, it may be a problem with the delimiter. It is desirable to recognize URLs and not insert separators into URLs.

### ISSUE THREAD

**Issue by yehuankun** [waylaidwanderer/node-chatgpt-api#295]
The URL cannot be opened and read accurately, it may be a problem with the delimiter. It is desirable to recognize URLs and not insert separators into URLs.
无法准确打开和读取网址，可能是分隔符的问题。希望能识别网址并且不给网址插入分隔符。

**Comment by waylaidwanderer** [comment]
Please open a proper bug report.
