### ISSUE TITLE
Add Dockerfile so this can be run under Docker

### ISSUE THREAD

**Issue by bertybuttface** [waylaidwanderer/node-chatgpt-api#3]
This is a good reference and I know it works on both ARM64 and AMD64: https://github.com/matrixgpt/matrix-chatgpt-bot/blob/main/Dockerfile

**Comment by waylaidwanderer** [comment]
I don't use Docker much, so PRs are welcome from people more experienced in this matter.

**Comment by thearchitectxy** [comment]
i am working on a DockerFile @waylaidwanderer @bertybuttface but it seems not to be able to a find a specific selector

`FROM satantime/puppeteer-node:19-slim

# We don't need the standalone Chromium
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
ENV CHROME_PATH=/usr/bin/google-chrome-stable
ENV DEBIAN_FRONTEND=noninteractive
# Install Google Chrome Stable and fonts
# Note: this installs the necessary libs to make the browser work with Puppeteer.
RUN apt-get update && apt-get install gnupg wget xvfb gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils libgbm-dev -y && \
  wget --quiet --output-document=- https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor > /etc/apt/trusted.gpg.d/google-archive.gpg && \
  sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
  apt-get update && \
  apt-get install google-chrome-stable -y --no-install-recommends && \
  rm -rf /var/lib/apt/lists/*

COPY . /src

WORKDIR /src



RUN npm install  -production


EXPOSE 3000

CMD xvfb-run npm start`



Error: │ TimeoutError: Waiting for selector `#__next .btn-primary` failed: Waiting failed: 180000ms exceeded

**Comment by tuannm151** [comment]
I forked the repo and create a Dockerfile and docker-compose as in https://github.com/tuannm151/node-chatgpt-api.
The server only listen on localhost so I have to change it to listen on all interface.

**Comment by bertybuttface** [comment]
> I forked the repo and create a Dockerfile and docker-compose as in https://github.com/tuannm151/node-chatgpt-api.
> The server only listen on localhost so I have to change it to listen on all interface.

This works well, I've been using it via docker-compose with:

```
version: '3.3'
services:
  chatgpt-api:
    command: "supervisord -c /app/supervisord.conf"
    container_name: chatgpt-api
    ports:
      - "3000:3000"
    build: https://github.com/tuannm151/node-chatgpt-api.git#main
    volumes:
      - './chatgpt-settings.js:/app/settings.js'
```

I was getting some permissions errors with the entrypoint script but the command line above solved that.

**Comment by bertybuttface** [comment]
This is an example of how something like this could be included in a project easily so the two parts are decoupled:

https://github.com/MatrixLLM/matrix-llm-bot

**Comment by queercat** [comment]
https://github.com/queercat/gpt-api-docker attempts to resolve this. Docker deployment currently works and can be sent to something like fly-io fairly trivially. Once #20 is resolved the Dockerfile will rely solely upon this repo and be fully stable.

![query](https://user-images.githubusercontent.com/22136781/216763915-0dec34f5-6f96-459b-92c1-c558bec030a8.gif)
