### ISSUE TITLE
TypeError: stream.getReader is not a function

### ISSUE THREAD

**Issue by MadeBugs** [waylaidwanderer/node-chatgpt-api#30]
`newuser@work % npm run cli

> @waylaidwanderer/chatgpt-api@1.10.3 cli
> node bin/cli.js

   ╔═══════════════╗
   ║  ChatGPT CLI  ║
   ╚═══════════════╝

Type "!" to access the command menu.
? Write a message: hi
TypeError: stream.getReader is not a function
    at getBytes (file:///Users/newuser/Documents/chatgpt/node-chatgpt-api/node_modules/@fortaine/fetch-event-source/lib/esm/parse.js:2:27)
    at create (file:///Users/newuser/Documents/chatgpt/node-chatgpt-api/node_modules/@fortaine/fetch-event-source/lib/esm/fetch.js:54:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Type "!" to access the command menu.
? Write a message: `

this is a bug? or my setting is error?

`export default {
    // Your OpenAI API key
    openaiApiKey: 'apikey' || '',
    chatGptClient: {
        // (Optional) Parameters as described in https://platform.openai.com/docs/api-reference/completions
        modelOptions: {
            // The model is set to text-chat-davinci-002-20221122 by default, but you can override
            // it and any other parameters here
            //model: 'text-chat-davinci-002-20221122',
	    model: 'text-davinci-003',
        },
        // (Optional) Set custom instructions instead of "You are ChatGPT...".
        // promptPrefix: 'You are Bob, a cowboy in Western times...',
        // (Optional) Set a custom name for the user
        // userLabel: 'User',
        // (Optional) Set a custom name for ChatGPT
        // chatGptLabel: 'ChatGPT',
        // (Optional) Set to true to enable `console.debug()` logging
        debug: false,
    },
    // Options for the Keyv cache, see https://www.npmjs.com/package/keyv.
    // This is used for storing conversations, and supports additional drivers (conversations are stored in memory by default)
    cacheOptions: {},
    // Options for the API server
    apiOptions: {
        port: process.env.API_PORT || 3000,
        host: process.env.API_HOST || 'localhost',
        // (Optional) Set to true to enable `console.debug()` logging
        debug: false,
    },
    // If set, ChatGPTClient will use `keyv-file` to store conversations to this JSON file instead of in memory.
    // However, `cacheOptions.store` will override this if set
    storageFilePath: process.env.STORAGE_FILE_PATH || './cache.json',
}`

**Comment by askie** [comment]
+1

**Comment by waylaidwanderer** [comment]
What version of Node.js are you running? Try upgrading to at least LTS version if it's older than that.

**Comment by askie** [comment]
v16.8.0
after upgrade to v18.14.0, all is right!
thx!

**Comment by waylaidwanderer** [comment]
v16 should be fully supported now
