### ISSUE TITLE
pandora in vps doesn't work

### ISSUE THREAD

**Issue by iknow2333** [waylaidwanderer/node-chatgpt-api#306]
**Describe the bug**
I trying to deploy pandora in AWS EC2,but there is nothing output even a warning when i type in
I've modified the .env and settings .js make their ports consistent,and it work in cli
The chat close quickly,and it's the same as turning off the API
I used caddy for reverse proxy to my personal domain

**To Reproduce**

**Expected behavior**

**Screenshots**
![屏幕截图 2023-04-13 234005](https://user-images.githubusercontent.com/103983460/231816204-37d42bc1-4bf1-410d-8816-35e72847fa7b.png)

**Node.js version (please complete the following information):**
 - OS: debian11
 - Node.js v18.16.0
 - npm 9.5.1

**Package version (please complete the following information):**
 - [e.g. 1.33.0]

**Additional context**

**Comment by waylaidwanderer** [comment]
More appropriate for a Help thread: https://github.com/waylaidwanderer/node-chatgpt-api/discussions/categories/help
