### ISSUE TITLE
how to reset a conversation on BingAIClient?

### ISSUE THREAD

**Issue by jegue** [waylaidwanderer/node-chatgpt-api#307]
I am knew to JS
so please any help will be appreciate
thanks

how to reset a conversation on BingAIClient?
after some time I got:
"Thanks for this conversation! I've reached my limit, will you hit “New topic,” please?"

thanks in Advance.

**Comment by waylaidwanderer** [comment]
Start a new conversation by using `sendMessage` without the conversation ID/signature/etc.
