### ISSUE TITLE
Model doesn't exist, again.

### ISSUE THREAD

**Issue by warrenrezane** [waylaidwanderer/node-chatgpt-api#31]
Seems like we are being played by OpenAI 😆 

![image](https://user-images.githubusercontent.com/19648576/217443413-ccb1c241-d5a3-4ab5-87b5-642a1abf8a18.png)

**Comment by waylaidwanderer** [comment]
That endpoint never worked with the leaked models

**Comment by warrenrezane** [comment]
Oh, sorry. My bad.
