### ISSUE TITLE
"That model is currently overloaded with other requests"

### ISSUE THREAD

**Issue by alikaptanoglu** [waylaidwanderer/node-chatgpt-api#32]
'That model is currently overloaded with other requests. You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID de79efb84259b34394b36c1f27bb548c in your message.)',
      type: 'server_error'

**Comment by waylaidwanderer** [comment]
You can use `text-davinci-003` if you don't mind paying for API usage. Otherwise, we can only wait until the model is not overloaded.

**Comment by jgontrum** [comment]
I'm getting the exact error, even though I can access ChatGPT just fine through their website using the same account. Does anyone have the same issue?

**Comment by FraglyGame** [comment]
I have the same issue ( "Failed to send message. HTTP 503 - Service Unavailable" )
Been having this problem since I woke up 8 hours ago, chatgpt works fine for me too ( on their website )

Is it possible that they patched this?

**Comment by jgontrum** [comment]
I have the feeling they're cracking down on this. Unfortunately, the browser-based version isn't working anymore either, because they either changed their layout or they got better at detecting puppeteer. Really bothers me because there is still no official API and I really wouldn't mind paying for it.

**Comment by waylaidwanderer** [comment]
@jgontrum From what I heard, the chatgpt npm package v3 still works, but you need to go back one patch version because OpenAI switched the model name back from the `-next` version.

I updated the readme:

> Even though `text-chat-davinci-002-20221122` is back up again, it seems like it's constantly overloaded and returns a 429 error. It's likely that OpenAI only dedicated a small amount of resources to this model to prevent it being widely used by the public. Additionally, I've heard that newer versions are now access-locked to OpenAI employees and partners, so it's unlikely that we'll be able to find any workarounds until the model is officially released.
> 
> You may use the `text-davinci-003` model instead as a drop-in replacement. Keep in mind that `text-davinci-003` is not as good as `text-chat-davinci-002` (which is trained via RHLF and fine-tuned to be a conversational AI), though results are still pretty good in most cases. **Please note that using `text-davinci-003` will cost you credits ($).**
> 
> I will be re-adding support for the browser-based ChatGPT for the API server and CLI. Please star and watch this repository for updates.
