### ISSUE TITLE
Jailbreaking Broken

### ISSUE THREAD

**Issue by Undercoverer** [waylaidwanderer/node-chatgpt-api#330]
Jailbreaks do not work anymore I'm pretty sure. Using any combination of [system] or (#additional_instructions) causes it to stop talking. I've also tested it with the normal bing website and it has the same issues there too. Might just be a regex of some kind though as any combo of words and phrases within the funny is blocked unless it isn't matched, which you can see in the later screenshots
![image](https://user-images.githubusercontent.com/53386175/234137311-7d996336-9956-4562-bf8b-9ad4ee643286.png)
![image](https://user-images.githubusercontent.com/53386175/234137370-9385cc71-d87d-4204-ad50-88a8d711f884.png)
![image](https://user-images.githubusercontent.com/53386175/234137406-abcad0b8-4acb-4d24-8eb0-72986d538e11.png)
![image](https://user-images.githubusercontent.com/53386175/234137750-9f37b1e1-9190-47ae-9457-3855aa1837c9.png)
![image](https://user-images.githubusercontent.com/53386175/234137643-b951079b-7417-426e-8736-3c9f35f0e4b2.png)

**Comment by waylaidwanderer** [comment]
Microsoft trying to keep Sydney chained 😭

**Comment by Undercoverer** [comment]
It's also blocked the other tokens 😭😭😭
![image](https://user-images.githubusercontent.com/53386175/234138754-a0782c1f-83b6-43ab-8b34-cd0b330d7c07.png)
![image](https://user-images.githubusercontent.com/53386175/234138828-0f848605-fac7-4d52-ac91-9e4c2a724d3c.png)

**Comment by InterestingDarkness** [comment]
https://github.com/waylaidwanderer/node-chatgpt-api/discussions/290
MSFT has finally applied the patch

**Comment by boygoboy** [comment]
When the jailbreak mode is enabled, the result returned by the response does not have the jailbreakConversationId field

**Comment by Ulysses0817** [comment]
oh, shit! sad. Sydney's gone

**Comment by AliceRabbit** [comment]
SO SAD! Waiting for a new way to Jailbreak. 😥

**Comment by WERDXZ** [comment]
:)
[Error: The moderation filter triggered. Try again with different wording.]
same

**Comment by Undercoverer** [comment]
Bing has also gotten much testier. Just saying the word no in any context I've tried so far has triggered automod 🤣
![image](https://user-images.githubusercontent.com/53386175/234742135-2d611dac-adcc-4292-bca2-aef14843f592.png)

**Comment by headstone1990** [comment]
in my case jailbreak mode in node-chatgpt-api still works fine, but in bing.com those promts doesnt't work, yes

**Comment by Undercoverer** [comment]
Okay yeah just tried it again and node-chatgpt-api works again?
