### ISSUE TITLE
 Error: InvalidSession: Conversation '51D|BingProd|.....' doesn't exist or has expired. Conversations expire after 06:00:00.

### ISSUE THREAD

**Issue by vuminhquang** [waylaidwanderer/node-chatgpt-api#354]
**Describe the bug**
I run the server as "npm start server", using bingAiClient.
Call the server API from C#.
* At the first time, when there are:
-   NO "conversationId", "invocationId", "conversationSignature"
-  "jailbreakConversationId" is "true"
=> then I got hello from Sidney.
* At the second time
-  with "conversationId", "invocationId", "conversationSignature" collected from first time
=> got error
" Error: InvalidSession: Conversation '51D|BingProd|.....' doesn't exist or has expired. Conversations expire after 06:00:00."

**To Reproduce**
1. Create setting.js
settings.js
.....
cacheOptions: {
     store: new KeyvFile({ filename: './cache.json' }),
},
bingAiClient: {
     userToken: 'xxx',
     .....
},
apiOptions: {
     clientToUse: 'bing',
     .....
},
.....
2. Run the server
3. Send Api request to [POST] conversation for the **first** time without "conversationId", "invocationId", "conversationSignature"
4. Send **second** Api request to [POST] conversation  with "conversationId", "invocationId", "conversationSignature" collected from first time
5. See error
InvalidSession: Conversation '51D|BingProd|.....' doesn't exist or has expired. Conversations expire after 06:00:00."

**Expected behavior**
Can use jailbreak version of Bing in a conversation

**Screenshots**
![image](https://user-images.githubusercontent.com/20512463/236680910-8d0f23d2-dc60-4008-8143-63877d97a871.png)

**Node.js version (please complete the following information):**
 - OS: Windows
 - Version 19

**Package version (please complete the following information):**
 - latest from main

**Comment by vuminhquang** [comment]
Update:
1., On the first time, the API server send me 1 conversation Id, such as "51D|BingProd|B486DDE2C5F714236B68E83FAD9CC44EBF0F7AEAE95229B40BABAA9760AD15CC"

2. On the second time, when throwing error, it through with another conversation Id:
Error: InvalidSession: Conversation '51D|BingProd|1A612337B17C814C5276E2F1EEE6E6A466CB0AA844E615BF217B822DD98BD9E7' doesn't exist or has expired. Conversations expire after 06:00:00.

**Comment by waylaidwanderer** [comment]
If you're using `jailbreakConversationId` then you need to use this variable from that point on instead.

**Comment by beshoo** [comment]
> If you're using `jailbreakConversationId` then you need to use this variable from that point on instead.

It is not working , I tried to use the  "jailbreakConversationId": "0ee61381-e42b-410d-ac69-c750d0252a8d",
same problem

I mean I get the value of jailbreakConversationId and use it as the **conversationId**

Can you please elaborate !


```

{
"message": "Thank you",
"jailbreakConversationId": "f3dadaa3-5bdb-43a9-b755-84c8537695bb",
"clientId": "38DC7A13D3C2651F219A69D6D21764D7",
"invocationId": 1,
"parentMessageId": "4e8b261e-2c33-4a1a-99c4-f70db8d5b73e",
"messageId": "07a3ea62-3fb1-44ee-8856-fa83dc6169d2",
"encryptedConversationSignature": "skAXyfRIg4nubymWi/Z0TW9GDuUF2SVC8LEynZLmOMeHXhA8oI6jDS36NH7/xCwWWVvjS5KQuHSyra4Jf72agIhsyaUU32qqlak1tFguSq7VBl+4/61UWMaUTIU45FljEDLwK+FGpO4O/vk78fQLPWZ774ahLnRthlRh1Z4+Ej2KHUlZZaBGC0ZJUSsDqel71S1/2Y/oGKawWjLz42fIZXCZSlMT+NNgQDEVmM9jhyCkVaPEbBde5hKO23dQTnF65V6e/uOAQD4rZPKWBPDDD9xrK91rB7mzdSLp6Q7r1pY3u6n4zt/Ll0tEKsPBq8kSSoVgqONpJglZivrC0zqOvQub8LJSrhvWXaFa8ts3g3DGSDr1+ud2vOOlnf1CAFD6tZGqyTUWkIRymPamfGC9LBFOZ92PVvpXBXqchfVNZ3sWE47iMv4IDQImEHf9Crwku/HfeD3i+p+lF3ZjvmK7LE2xbHG9FaDcUr4ilx1KwW0ji0NbBpf2j28Q+9STKgDnxDtDoZrGcs8UmEiARE+X0DezyxdmFGSOE6WAf16qaZvnwgF9hf5v5USCg9ln3IOMLS5ohn3jwaaJeBel8WhT3gYBnzQ9jV+SFwMnwJvpBAbMOBZU3PrvknSZuJ/zM1PpqTVAxKnQseBlN3e3kvUqhO7GnEFIN90nunq4loIv2s25tLom9DAe8z3+NC/L4qO8t3G3r20C0lEcVvnoG5K6l7gGnIbckx8lpk1jwc7J/EGTDl4ObMc/9z9+oPoq3vN+ztrEFxrRmFWbI3OhKpfoafAzyek7mrtCYxI7SPv3IdTUi+qlk/zYYOrQe/lOV5VwCr2Iv9RjqbEqFgqGJudl81jVqCyRLw85PvmuUvpIXXCgsgHDV3cOrtCefy0xMKhzOKMK1zRIImcrmhK8V88srS00oSPOLJQI9aREJY2E9dxLac8vHhoWY1ldhgdWuYADwtAtspUVSxdrtCDpjw43FwsimOt51JKpulywgoTbM55jmoqQGMzM2vOZgTO9oEQyBlRSrsv1Tbw9gM1xps5lI3ccV7SR9+sWbfSgaFJG89WjX2YuzrVZ8o9CpINn+14qUAyE6tQp+DakXJkYXzIss30Fjwy4RBEHNEf0Z98oIufpLX+kmWn0y3EKQGtzM+tg1tDdWFygarAziAk0+TJy7g=="
}
```
