### ISSUE TITLE
hello ,there is no respond after i run the demo,and i fill out the userToken

### ISSUE THREAD

**Issue by zjrwtx** [waylaidwanderer/node-chatgpt-api#36]
![image](https://user-images.githubusercontent.com/86822589/217790494-39cfca28-4f0b-483a-abbd-19745d6a409a.png)

**Comment by waylaidwanderer** [comment]
It doesn't work if you're still on the wait list

**Comment by zjrwtx** [comment]
> It doesn't work if you're still on the wait list

got it ，thanks
