### ISSUE TITLE
The Moderation tag is triggered no matter what I ask

### ISSUE THREAD

**Issue by BarryAllen-Arrow** [waylaidwanderer/node-chatgpt-api#366]
**Describe the bug**
The Moderation tag is triggered no matter what I ask

**To Reproduce**
Ask any question in the jailbreak mode

**Expected behavior**
It will return "Error: The moderation filter triggered. Try again with different wording."

**Comment by yxygg** [comment]
same problem.now i cant use the jailbreak mode of newbing

**Comment by owlcloud** [comment]
what to do? is everyone like this?

**Comment by InterestingDarkness** [comment]
https://github.com/waylaidwanderer/node-chatgpt-api/pull/350 fixed it

**Comment by minatoAI** [comment]
> #350 fixed it

great work! have tried and Sydney back

**Comment by adi6409** [comment]
Great! Been having this issue yesterday. Before switching to that pr, are there any changes? New syntax or anything? Or is it a plug&play upgrade?

**Comment by HailHydra58** [comment]
> 伟大！昨天一直有这个问题。在切换到该 pr 之前，是否有任何更改？新语法还是什么？还是即插即用升级？

Same question

**Comment by InterestingDarkness** [comment]
It's a plug and play upgrade

**Comment by adi6409** [comment]
Awesome, thank you!

**Comment by waylaidwanderer** [comment]
Published v1.36.0 with this fix. Thanks @InterestingDarkness
