### ISSUE TITLE
bing

### ISSUE THREAD

**Issue by Kucklovod00** [waylaidwanderer/node-chatgpt-api#37]
what are the limits in bing?

**Comment by waylaidwanderer** [comment]
The input message is limited to 2000 characters, and the AI's response is roughly 1000 tokens. Anything else I'm not sure about yet

**Comment by Kucklovod00** [comment]
how many requests per minute?

**Comment by waylaidwanderer** [comment]
No idea yet, I didn't want to abuse it too much

**Comment by waylaidwanderer** [comment]
But it doesn't seem like there is much rate limiting

**Comment by Kucklovod00** [comment]
you can check? send 20 requests per minute, for example

**Comment by waylaidwanderer** [comment]
It's not my account so I don't want to cause any issues. Feel free to update this issue with the answer when you get access and find out yourself.
