### ISSUE TITLE
Sydney  [Error: The moderation filter triggered. Try again with different wording.]"

### ISSUE THREAD

**Issue by boygoboy** [waylaidwanderer/node-chatgpt-api#387]
{
  "conversationId": "51D|BingProd|ABD10BA60304E501A1CE4A3BFF181FADFC4AA10BFDF5891276E54B1940B45B24",
  "conversationSignature": "ZgUp/FGcfwNOn6gV7g5oJrTx1b/QsmpZSyIvZ8i/h/E=",
  "clientId": "1055518460391200",
  "invocationId": 1,
  "conversationExpiryTime": "2023-05-27T15:34:50.0353858Z",
  "response": "[Error: The moderation filter triggered. Try again with different wording.]",
  "details": {
    "hiddenText": "Sorry! That’s on me, I can’t give a response to that right now. What else can I help you with?",
    "author": "bot",
    "createdAt": "2023-05-27T09:34:49.6404541+00:00",
    "timestamp": "2023-05-27T09:34:49.6404541+00:00",
    "messageId": "656e0a63-ff51-431c-83fd-3793e487ca1d",
    "requestId": "a4b7702b-009d-45ad-81aa-2623a2c83e78",
    "offense": "None",
    "adaptiveCards": [
      {
        "type": "AdaptiveCard",
        "version": "1.0",
        "body": [
          {
            "type": "TextBlock",
            "text": "[Error: The moderation filter triggered. Try again with different wording.]",
            "wrap": true
          }
        ]
      }
    ],
    "sourceAttributions": [],
    "feedback": {
      "tag": null,
      "updatedOn": null,
      "type": "None"
    },
    "contentOrigin": "Apology",
    "privacy": null,
    "spokenText": "Sorry! That’s on me, I can’t give a response to that right now. What else can I help you with?",
    "text": "[Error: The moderation filter triggered. Try again with different wording.]"
  },
  "jailbreakConversationId": "600be373-a93a-4308-a2ef-8155c4a5c1b0",
  "parentMessageId": "f55c2b10-4435-4d5e-a72e-e66caac1b9ab",
  "messageId": "d7997f7c-9f55-47b7-9e45-68fd65513557"
}
The above is the error message

**Comment by waylaidwanderer** [comment]
Seems to be working fine as of `@waylaidwanderer/chatgpt-api@1.36.3` with jailbreak mode enabled.
