### ISSUE TITLE
how to enable Jailbreaking(Sydney) mode 

### ISSUE THREAD

**Issue by Maddaxman** [waylaidwanderer/node-chatgpt-api#388]
How to activate Jailbreaking (Sydney) mode? I see that jailbreakConversationId has already been set to true, but it is still using the normal Bing mode.

I'm using in API Server mode

**Comment by waylaidwanderer** [comment]
See the demo starting on this line: https://github.com/waylaidwanderer/node-chatgpt-api/blob/main/demos/use-bing-client.js#L61

**Comment by waylaidwanderer** [comment]
Additionally, see https://github.com/waylaidwanderer/node-chatgpt-api#endpoints on how to use those parameters via the API.

**Comment by waylaidwanderer** [comment]
Please don't open bug issues for simple questions in the future. You can ask for help in the Help section of the Discussions page next time.

**Comment by Maddaxman** [comment]
> https://github.com/waylaidwanderer/node-chatgpt-api/blob/main/demos/use-bing-client.js#L61

OK
