### ISSUE TITLE
text in req is null when use bing

### ISSUE THREAD

**Issue by tvtienhn0610** [waylaidwanderer/node-chatgpt-api#40]
I use your library when I call to get the answer and only get null text results

{
  author: 'bot',
  id: '4e9561bb-7e67-471f-b950-dc028e8729ed',
  conversationId: undefined,
  clientId: undefined,
  conversationSignature: undefined,
  invocationId: '2',
  text: ''
}

**Comment by waylaidwanderer** [comment]
Does your account have access to Bing Chat? Also show me your code

**Comment by tvtienhn0610** [comment]
how to get access to bing chat

**Comment by tvtienhn0610** [comment]
const api = new BingChat({
            cookie:'16C6V-qMJ8F-79XoV9VHQrv3Eb8ymqdOWNKzij29_3snDG3ldecujydCxmGoOm9o3R4FTaGaWU_P7iZR3hyDNQ9TR5OZ6UUvNBrhxuFF3wMVZi4qQvoeS8EE-wJ_6HxpQG699jn3fj3neocS_PTIM6uT4Kig42g9aPBBQGLjMHuS3unr0T1OVJR0AkE4G5YUM'})
        const res = await api.sendMessage('write a 500 word essay on frogs' , {
            onProgress: (token) => console.log(token.text)
        })

        console.log(res)

**Comment by waylaidwanderer** [comment]
I think you're posting the issue in the wrong repo... my client is called `BingAIClient` and the options are different.
