### ISSUE TITLE
model not found

### ISSUE THREAD

**Issue by gregoryStarr** [waylaidwanderer/node-chatgpt-api#41]
It looks like the model is no longer available... 
<img width="1218" alt="settings js — node-chatgpt-api 2023-02-10 06-49-06" src="https://user-images.githubusercontent.com/6515805/218085714-cd6e5010-7478-4561-85d7-81d08677c759.png">

**Comment by waylaidwanderer** [comment]
Yeah, they removed it entirely. I'll update the readme to make a note of it later.

**Comment by waylaidwanderer** [comment]
New model has been found https://github.com/waylaidwanderer/node-chatgpt-api/releases/tag/v1.13.0
