### ISSUE TITLE
Authorization to access BingAIClient

### ISSUE THREAD

**Issue by danielmaela04** [waylaidwanderer/node-chatgpt-api#42]
Hello,
I would like to get authorization to access and use the BingAIClient since I got the necessary "-U" cookie.

Could you explain to me how I can get authorization to access the project?

Message: 
**_"result":{"value":"UnauthorizedRequest","message":"The conversationSignature is not set and is required to ensure that you have permission to use our APIs. IsAuthenticated=False. App ID=","error": "UnauthorizedRequest"_**

thanks in advance for your help.

**Comment by waylaidwanderer** [comment]
Does your account have access to Bing Chat? If not, you won't be able to use this client.
