### ISSUE TITLE
Error: AbortController is not defined in node 14. Please add support for node 14

### ISSUE THREAD

**Issue by putuoka** [waylaidwanderer/node-chatgpt-api#422]
![image](https://github.com/waylaidwanderer/node-chatgpt-api/assets/20880839/b089e8fa-8709-4a3a-9604-f057bf627a13)

**Comment by putuoka** [comment]
Solved by 
npm i node-abort-controller
npm i node-fetch

then

import fetch from "node-fetch";
import { AbortController } from "node-abort-controller";

**Comment by Erisfiregamer1** [comment]
Hey, quicktip. Check the README next time: It states support for node 16 and above only. That's why that problem arose for you :)
