### ISSUE TITLE
disconnected Error: Unexpected server response: 200

### ISSUE THREAD

**Issue by xuxin3101** [waylaidwanderer/node-chatgpt-api#437]
![image](https://github.com/waylaidwanderer/node-chatgpt-api/assets/29241434/30af6815-7f26-42b1-894b-6892dbd11b58)
When I initiate a session it shows this

**Comment by aiqinxuancai** [comment]
I am currently also experiencing this error, updating cookies does not solve the issue either, the account seems to be normal and can be used properly on the web NewBing.
