### ISSUE TITLE
git pull and npm run server error:still model not exist? 

### ISSUE THREAD

**Issue by zjrwtx** [waylaidwanderer/node-chatgpt-api#44]
![image](https://user-images.githubusercontent.com/86822589/218242442-16aa11d9-2b7a-44d2-8889-fe1679c4c322.png)
![image](https://user-images.githubusercontent.com/86822589/218242466-d7a03503-5d57-4aa7-adda-1a4f592969b1.png)

**Comment by waylaidwanderer** [comment]
Make sure you remove any model from your settings.js

**Comment by zjrwtx** [comment]
> Make sure you remove any model from your settings.js

thanks,it works!

**Comment by waylaidwanderer** [comment]
I just updated the README/examples to comment it out by default so others don't get confused :)
