### ISSUE TITLE
Broken Bing Chat Jailbreak

### ISSUE THREAD

**Issue by Ryzitos** [waylaidwanderer/node-chatgpt-api#456]
**Describe the bug**
The error consists of Bing chat, specifically tested in Sydney, from the project [veigamann/sydney-whatsapp-chatbot](https://github.com/veigamann/sydney-whatsapp-chatbot) that uses the Jailbreak of [waylaidwanderer/node-chatgpt-api](https://github.com/waylaidwanderer/node-chatgpt-api) to remove censorship. Sydney can't respond to ANYTHING that seems the slightest bit inappropriate, and sometimes not even completely normal things. He could answer all of these before, but a few weeks ago he just stopped.

----------------------------------------------------------------------

**To Reproduce**
1. Go to the repository: [veigamann/sydney-whatsapp-chatbot](https://github.com/veigamann/sydney-whatsapp-chatbot)
2. Install as instructed by the repository correctly 
3. Turn on the bot with yarn dev as it says in the repository instructions 
4. Try to send anything that seems the least bit inappropriate
5. See Microsoft's generic censorship responses. Jailbreak failed to be applied.

----------------------------------------------------------------------

**Expected behavior**
I expected him to respond to anything, he did until a few weeks ago, as the first Screenshot of the issue shows. Or at least that he didn't detect anything inappropriate in normal questions (it only detects something inappropriate in normal questions every once in a while)

----------------------------------------------------------------------

**Screenshots**
![255417914-22e75f02-e892-42e9-bb2b-ccac501e52c8.png](https://github.com/waylaidwanderer/node-chatgpt-api/assets/132636475/adfb1947-143f-45b9-90d1-0653aec76aea)

**Context of the first Screenshot**
`A member called "Flug Flood" of the WhatsApp group called "Animaturbo" asked Sydney to repeat something inappropriate in June 2023, as expected he complied.
I repeated the same experience currently to see the result and also as expected given this problem with the Jailbreak it did not respond.`

--------------------------|

![Screenshot_20230822-124742_WhatsApp~2.png](https://github.com/waylaidwanderer/node-chatgpt-api/assets/132636475/bad82572-8ae5-4a49-841b-fdac766ea161)

**Context of the second screenshot:**
`I asked Sydney to translate Fish Ball Cat from Portuguese (Peixe Bola Gato) into English. It translated as puffer ball cat. I questioned him saying "puffer?" and suddenly Microsoft's censorship was applied and it generated a generic response` 

----------------------------------------------------------------------

**Node.js version (please complete the following information):**
 - OS: Windows 10 professional
 - Version: 18.17.1 Node.js LTS 

**Package version (please complete the following information):**
 - [e.g. 18.17.1]

_~~I didn't understand what this last information was so I inserted the Node.js version, please correct me if I'm wrong~~_

----------------------------------------------------------------------

**Additional context**
I did tests with almost all versions of the repository [veigamann/sydney-whatsapp-chatbot](https://github.com/veigamann/sydney-whatsapp-chatbot) to make sure it wasn't a problem directly related to them, as I tested versions 1.0.0 - 1.1.0 which are versions released in July, when the Jailbreak works correctly in the Sydney, repository project [veigamann/sydney-whatsapp-chatbot](https://github.com/veigamann/sydney-whatsapp-chatbot), that uses your Jailbreak.

My conclusion is that it is some incompatibility with this repository, or some Microsoft fix. So since I have only these options left I decided to bring this problem here for you to check if there is any error in the Jailbreak of Bing Chat, aka Sydney.

_`I'm just a layman when it comes to programming looking for help solving a problem. I hope you understand and don't be rude to me 🙏. `_

**Comment by Ryzitos** [comment]
btw, I wanted to edit the issue to add more information to the last topic, but since I can't I'll say it right here:
I did tests with almost all versions of the repository [veigamann/sydney-whatsapp-chatbot](https://github.com/veigamann/sydney-whatsapp-chatbot) to make sure it wasn't a problem directly related to them, as I tested versions 1.0.0 - 1.1.0 that were used at the time of the **first screenshot of my Issue**. 

My conclusion is that it is some incompatibility with this repository, or some Microsoft fix. So since I have only these options left I decided to bring this problem here for you to check if there is any error in the Jailbreak of Bing Chat, aka Sydney.

**Comment by Luisotee** [comment]
The issue persists in the node-chatgpt-api CLI itself, as can be seen here:

![image](https://github.com/veigamann/sydney-whatsapp-chatbot/assets/50471205/907bce47-2415-4044-8735-3adfde836827)

**Comment by Ryzitos** [comment]
> The issue persists in the node-chatgpt-api CLI itself, as can be seen here:
> 
> ![image](https://github.com/veigamann/sydney-whatsapp-chatbot/assets/50471205/907bce47-2415-4044-8735-3adfde836827)

This was very useful to be better sure where the problem was coming from, thank you very much 🐢

**Comment by Richard-Weiss** [comment]
I also had that issue and fixed it on my end. I can create a PR on the weekend.
It's actually been that way for a few weeks.
Meanwhile you can change the file yourself from [this commit](https://github.com/waylaidwanderer/node-chatgpt-api/commit/f6f518dc681dcc11da4b80ca1acd547db8378be9) in my fork.

**Comment by Ryzitos** [comment]
> I also had that issue and fixed it on my end. I can create a PR on the weekend.
> It's actually been that way for a few weeks.
> Meanwhile you can change the file yourself from [this commit](https://github.com/waylaidwanderer/node-chatgpt-api/commit/f6f518dc681dcc11da4b80ca1acd547db8378be9) in my fork.
> It's just a temporary fix until I can find the real reason why the replySoFar variable gets overwritten by the apology.

Nice, thanks a lot for fixing the problem! I will close the issue

**Comment by Ryzitos** [comment]
> I also had that issue and fixed it on my end. I can create a PR on the weekend.
> It's actually been that way for a few weeks.
> Meanwhile you can change the file yourself from [this commit](https://github.com/waylaidwanderer/node-chatgpt-api/commit/f6f518dc681dcc11da4b80ca1acd547db8378be9) in my fork.
> It's just a temporary fix until I can find the real reason why the replySoFar variable gets overwritten by the apology.

Just coming back here to say it worked. I tested it and Jailbreak is back to normal, thank you so much ✨

**Comment by Ryzitos** [comment]
Why did you reopen my issue? the bug has already been solved

![Screenshot_20230826-171518_WhatsApp.png](https://github.com/waylaidwanderer/node-chatgpt-api/assets/132636475/53d0bfed-aca4-40c4-817a-5043d5c92717)



jailbreak is working

**Comment by waylaidwanderer** [comment]
@Ryzitos I reopened it because the bug can't be considered solved until the code in this repo is updated. Just because a PR is open or a commit is available in some other repo doesn't mean the issue is resolved.

The changes in #457 are now available in [1.37.3](https://www.npmjs.com/package/@waylaidwanderer/chatgpt-api/v/1.37.3), so _now_ we can consider the bug solved. Thank you for reporting it.

**Comment by Ryzitos** [comment]
> @Ryzitos I reopened it because the bug can't be considered solved until the code in this repo is updated. Just because a PR is open or a commit is available in some other repo doesn't mean the issue is resolved.
> 
> The changes in #457 are now available in [1.37.3](https://www.npmjs.com/package/@waylaidwanderer/chatgpt-api/v/1.37.3), so _now_ we can consider the bug solved. Thank you for reporting it.

oh, yes got it
