### ISSUE TITLE
That model does not exist

### ISSUE THREAD

**Issue by thechen130** [waylaidwanderer/node-chatgpt-api#46]
![image](https://user-images.githubusercontent.com/74664452/218244165-da24ba05-9777-4105-a872-f595f9a6f641.png)
![image](https://user-images.githubusercontent.com/74664452/218244188-b4d13869-350d-470e-bffb-ef4c1c05d9c0.png)

**Comment by waylaidwanderer** [comment]
Yeah, unfortunately, it looks like they disabled access to the model. Bad timing 😅

**Comment by thechen130** [comment]
换成了text-chat-davinci-002也不行，只有text-davinci-003可以

**Comment by waylaidwanderer** [comment]
That's correct.

**Comment by getxd-dev** [comment]
> That's correct.

just curious, how did you find the new model?

**Comment by helperAI** [comment]
> 

你设置了davinci-003模型之后，能够正常跑起来吗？我运行还是报： That model does not exist

**Comment by waylaidwanderer** [comment]
Please check out https://github.com/waylaidwanderer/node-chatgpt-api/releases/tag/v1.14.0

**Comment by waylaidwanderer** [comment]
Do note that there are caveats when using this method, as mentioned in my readme.
