### ISSUE TITLE
My account has been removed from the waiting list, but running `use-bing-client.js` returns the following:

### ISSUE THREAD

**Issue by eamd-wq** [waylaidwanderer/node-chatgpt-api#48]
My account has been removed from the waiting list, but running `use-bing-client.js` returns the following:

node .\use-bing-client.js

performing handshake

handshake established

1. ---------------------------
{"arguments":[{"source":"cib","optionsSets":["nlu_direct_response_filter","deepleo","enable_debug_commands","disable_emoji_spoken_text","responsible_ai_policy_235","enablemm"],"isStartOfSession":true,"message":{"author":"user","inputMethod":"Keyboard","text":"Write a short poem about cats","messageType":"Chat"},"participant":{}}],"invocationId":"0","target":"chat","type":4}
2. --------------------------
[{"type":2,"invocationId":"0","item":{"firstNewMessageIndex":null,"suggestedResponses":null,"conversationId":"7104db73-d7ed-4428-baa3-3ab8f406e816","requestId":"4c647392-28de-4bcb-b0ff-c9a30be92cca","telemetry":{"metrics":null,"startTime":"2023-02-12T04:07:52.1888796Z"},"result":{"value":"UnauthorizedRequest","message":"The conversationSignature is not set and is required to ensure that you have permission to use our APIs. IsAuthenticated=False. App ID=","error":"UnauthorizedRequest","renewCert":true,"serviceVersion":"20230210.12"}}},{"type":3,"invocationId":"0"}]

**Comment by waylaidwanderer** [comment]
Have you updated this part to set your token?

```JS
const bingAIClient = new BingAIClient({
    userToken: '', // "_U" cookie from bing.com
    debug: false,
});
```

You can email me your `_U` token privately if you want me to test it. Maybe Bing changed something recently. I don't have access yet, so I've been relying on other people's access.

**Comment by eamd-wq** [comment]
> 您是否更新了此部分以设置您的令牌？
> 
> ```js
> const bingAIClient = new BingAIClient({
>     userToken: '', // "_U" cookie from bing.com
>     debug: false,
> });
> ```
> 
> `_U`如果你想让我测试它，你可以私下给我发邮件给我你的令牌。也许 Bing 最近改变了什么。我还没有访问权限，所以我一直依赖其他人的访问权限。

I'm sure the token is up to date; I can find your E-mail address there;

**Comment by eamd-wq** [comment]
> Have you updated this part to set your token?
> 
> ```js
> const bingAIClient = new BingAIClient({
>     userToken: '', // "_U" cookie from bing.com
>     debug: false,
> });
> ```
> 
> You can email me your `_U` token privately if you want me to test it. Maybe Bing changed something recently. I don't have access yet, so I've been relying on other people's access.

I found the mailbox on your home page and have sent my token

**Comment by waylaidwanderer** [comment]
@eamd-wq Thanks for sharing the token. I set it in the `userToken` in `demos/use-bing-client.js` and it works for me. Are you still having issues?

**Comment by Nitesh-Singh-5** [comment]
Hi @waylaidwanderer, I don't see `_U` cookie in bing.com

**Comment by eamd-wq** [comment]
> @eamd-wq Thanks for sharing the token. I set it in the `userToken` in `demos/use-bing-client.js` and it works for me. Are you still having issues?

Not at present. If you still need a token, you can send me an email.
