### ISSUE TITLE
That model does not exist'

### ISSUE THREAD

**Issue by newdots** [waylaidwanderer/node-chatgpt-api#49]
status: 404,
  json: {
    error: {
      message: 'That model does not exist',
      type: 'invalid_request_error',
      param: null,
      code: null
    }

**Comment by waylaidwanderer** [comment]
OpenAI disabled access to the models via the official API. If you still want to use them, you can use the reverse proxy/private API server as documented in the readme.

**Comment by newdots** [comment]
i use the example reverse but ,reply this 

status: 429,
  json: {
    status: false,
    error: 'You are rate-limited Rate-limited or API key is invalid'
  }

**Comment by ikechan8370** [comment]
> i use the example reverse but ,reply this
> 
> status: 429, json: { status: false, error: 'You are rate-limited Rate-limited or API key is invalid' }

the same error. But it was fine five minutes ago

**Comment by newdots** [comment]
it's OPENAI_API_KEY setting error ,
`Set the OpenAI API key to your ChatGPT session's access token instead of your actual OpenAI API key.
You can find your ChatGPT session's access token by logging in to [ChatGPT](https://chat.openai.com/) and then going to https://chat.openai.com/api/auth/session (look for the accessToken property).
Fetching or refreshing your ChatGPT session's access token is not currently supported by this library.`


but the other question is, reverse endpoint reply this
`"model":"text-davinci-002-render"}`
so i can't use text-davinci-003 when i set the model text-davinci-003-render

**Comment by ikechan8370** [comment]
> > i use the example reverse but ,reply this
> > status: 429, json: { status: false, error: 'You are rate-limited Rate-limited or API key is invalid' }
> 
> the same error. But it was fine five minutes ago

solved. I missed a letter in the token. The error message is a bit confusing.

**Comment by waylaidwanderer** [comment]
>  so i can't use text-davinci-003 when i set the model text-davinci-003-render

Right, if you're trying to use non-ChatGPT models then don't use the private API server.
