### ISSUE TITLE
You are rate-limited Rate-limited or API key is invalid

### ISSUE THREAD

**Issue by JerryWn12** [waylaidwanderer/node-chatgpt-api#50]
using reverse proxy
proxy: https://chatgpt.pawan.krd/api/completions
module: text-davinci-002-render
api_key: https://chat.openai.com/api/auth/session's accessToken

**Comment by JerryWn12** [comment]
fixed

**Comment by PwLDev** [comment]
How did you fixed it? I'm having the same problem

**Comment by waylaidwanderer** [comment]
I heard it might be a bug with Pawan's API server. Use a free account with the `text-davinci-002-render` model.

**Comment by kilingzhang** [comment]
+1

**Comment by AutumnWhj** [comment]
How did you fixed it? I'm having the same problem

**Comment by JerryWn12** [comment]
I didn't do anything it just work automaticly🥲sorry just see the message

**Comment by AutumnWhj** [comment]
can you share your config ? 👁

**Comment by JerryWn12** [comment]
```
module.exports = {
    openaiApiKey: process.env.OPENAI_API_KEY || 'access_token_got_from_https://chat.openai.com/api/auth/session',
    chatGptClient: {
        reverseProxyUrl: 'https://chatgpt.pawan.krd/api/completions',
        modelOptions: {
            model: 'text-chat-davinci-002',
        },
        debug: false,
    },
    cacheOptions: {},
    bingAiClient: {
        userToken: '',
        debug: false,
    },
    apiOptions: {
        port: process.env.API_PORT || 3000,
        host: process.env.API_HOST || 'localhost',
        debug: false,
    },
    storageFilePath: process.env.STORAGE_FILE_PATH || './cache.json',
};
```
here is my config @AutumnWhj

**Comment by waylaidwanderer** [comment]
I see you set the `model` to `text-chat-davinci-002`. I think Pawan's API sets it to the `text-davinci-002-render` model if you don't give it a correct model name (like in your case), so keep that in mind.

**Comment by JerryWn12** [comment]
> 

Thanks i will check my available module

**Comment by kilingzhang** [comment]
Still no effect  ಥ_ಥ  @AutumnWhj Does it work?

**Comment by waylaidwanderer** [comment]
Trying @acheong08's API server instead: https://chat.duti.tech/completions

Let me know if it works for you guys
