### ISSUE TITLE
Please change CRLF to LF to prevent "env: node\r: No such file or directory"

### ISSUE THREAD

**Issue by h4x3rotab** [waylaidwanderer/node-chatgpt-api#51]
On Mac, when running cli server locally with `npx chatgpt-cli` results in error message:

```
env: node\r: No such file or directory
```

Apparently the problem is the CRLF EOL in `cli.js` not being recognized by the bash interpreter on macOS as described [here](https://stackoverflow.com/questions/30344858/node-script-executable-not-working-on-mac-env-node-r-no-such-file-or-directo). By converting CRLF to LF manually, the script works fine.

**Comment by waylaidwanderer** [comment]
Hmm, I thought git was supposed to convert it automatically when I push. I'll look into this, thank you.
