### ISSUE TITLE
Error: UnauthorizedRequest: Sorry, you are not allowed to access this service.

### ISSUE THREAD

**Issue by taishi55** [waylaidwanderer/node-chatgpt-api#54]
Question again!

I am still on waitlist. My user id on cookie is not working....
Is there any way to get this around?

**Comment by waylaidwanderer** [comment]
No, it won't work if you don't have access. Ask a friend for their token :D

**Comment by MARS-J** [comment]
So now,can't use pandoraAI with no setting token or something else right?
