### ISSUE TITLE
param user

### ISSUE THREAD

**Issue by Kucklovod00** [waylaidwanderer/node-chatgpt-api#62]
![image](https://user-images.githubusercontent.com/46756368/218312304-db9cc4e0-fe59-457f-881d-3a186439801a.png)

please add "user" parameter

**Comment by waylaidwanderer** [comment]
Please explain your use-case

**Comment by Kucklovod00** [comment]
What do you mean?

**Comment by waylaidwanderer** [comment]
I mean why do you need to do this?

**Comment by Kucklovod00** [comment]
to identify users and in case of violations of the rules, chatgpt will notify me

**Comment by waylaidwanderer** [comment]
Are you using text-davinci-003 then? It's not really applicable for other models.

**Comment by Kucklovod00** [comment]
> Вы используете text-davinci-003? Для других моделей это не совсем применимо.

yes

**Comment by waylaidwanderer** [comment]
Okay, I'll make a note. Closing this as a duplicate of #28 as it can be part of the same enhancement.
