### ISSUE TITLE
Using a Reverse Proxy 这个反向代理网站失效了，用上了cloudflare 没法用了

### ISSUE THREAD

**Issue by newdots** [waylaidwanderer/node-chatgpt-api#63]
没法用了哦

**Comment by waylaidwanderer** [comment]
English?

**Comment by 1765659645** [comment]
> 
How long is the validity period of accesstoken when using reverse proxy?

**Comment by newdots** [comment]
Using a Reverse Proxy in readme  is useless.

**Comment by waylaidwanderer** [comment]
@1765659645 not sure, but it lasted at least overnight for me. I haven't done extensive testing yet.

@newdots could you please clarify?

**Comment by newdots** [comment]
<img width="572" alt="image" src="https://user-images.githubusercontent.com/114389694/218427172-d9df126a-ebdd-4f3f-aab3-29a6f5980575.png">
this is my settings.js, yestoday it works but today i can't get the right reply now

**Comment by waylaidwanderer** [comment]
@newdots Seems like Pawan's server is having issues. I made a reverse proxy server today as well. Replace `reverseProxyUrl`'s value with `https://chatgpt.hato.ai/completions` instead to use mine and let me know if it works.

**Comment by JerryWn12** [comment]
use model text-chat-002-render

**Comment by waylaidwanderer** [comment]
Right, you also need to set model to "text-davinci-002-render" if you're on a free account or "text-davinci-002-render-paid" for plus accounts.

**Comment by JerryWn12** [comment]
add `model: text-davinci-002-render` in modelOptions

**Comment by zjrwtx** [comment]
> add `model: text-davinci-002-render` in modelOptions

still not work
![image](https://user-images.githubusercontent.com/86822589/218457311-7e3c88d6-2888-4891-80eb-61575a43c24e.png)

**Comment by newdots** [comment]
sorry i get this error
<img width="708" alt="image" src="https://user-images.githubusercontent.com/114389694/218482778-c41bf186-42ef-4140-8e60-4f08e4fe6c9f.png">

**Comment by newdots** [comment]
this is my settings

**Comment by newdots** [comment]
i modify the source,now it works
<img width="652" alt="image" src="https://user-images.githubusercontent.com/114389694/218483857-5102f5d4-0ffd-44f7-bba5-99163e9b4c29.png">

**Comment by newdots** [comment]
could you please open source the proxy, i  think it's very important. thanks

**Comment by JerryWn12** [comment]
why does it works? when `message.data === ''`, the `message.data !== ''` and `!message.data` always return `true`, if it truly worked, welcome PR.

**Comment by waylaidwanderer** [comment]
@newdots that bug was already fixed with the latest version, before I gave you guys the url for my reverse proxy server. Just make sure to update to the latest version.

**Comment by waylaidwanderer** [comment]
I can't open-source the code for the reverse proxy as we are keeping the method private to avoid it being patched by OpenAI.
