### ISSUE TITLE
new reverse proxy url  not work

### ISSUE THREAD

**Issue by zjrwtx** [waylaidwanderer/node-chatgpt-api#67]
![image](https://user-images.githubusercontent.com/86822589/218459531-355ec195-fd19-4484-afa0-a30590bb814b.png)
![image](https://user-images.githubusercontent.com/86822589/218459570-87cfd5a5-9e42-40f1-8e5e-38b2f90d5f26.png)

**Comment by waylaidwanderer** [comment]
@zjrwtx what error message are you getting?

**Comment by waylaidwanderer** [comment]
Whatever issue you're having has likely been fixed. Please re-open this issue if you're still having problems.
