### ISSUE TITLE
There was an error communicating with ChatGPT

### ISSUE THREAD

**Issue by a0709** [waylaidwanderer/node-chatgpt-api#68]

**Comment by a0709** [comment]
What conditions could cause this problem?

**Comment by funtuan** [comment]
@a0709 same error.

**Comment by waylaidwanderer** [comment]
@a0709 @funtuan first of all make sure that your prompt is less than 4097 tokens - max tokens. I'll add special handling so that this error is passed back to you. 

The error can also happen if the servers are overloaded.

**Comment by waylaidwanderer** [comment]
(I'm assuming you're using my reverse proxy)

**Comment by waylaidwanderer** [comment]
Updated the reverse proxy server to display some more user errors back to the user instead of showing a generic error message.

**Comment by funtuan** [comment]
I successfully get the error log `Error: Failed to send message. HTTP 400 - {"error":"Invalid model"}` in the console
changing the model setting to text-davinci-002-render, it can work. 
Thank you very much.

**Comment by pfeducode** [comment]
> `Error: Failed to send message. HTTP 400 - {"error":"Invalid model"}`我成功地在控制台中获得错误日志
> ，将模型设置更改为 text-davinci-002-render，它可以工作。
> 非常感谢。

what's your means, how to set?

**Comment by funtuan** [comment]
@pfeducode you can try it
```
chatGptClient: {
    modelOptions: {
        model: 'text-davinci-002-render',
    },
}
```
