### ISSUE TITLE
Reverse Proxy Code?

### ISSUE THREAD

**Issue by z0lo13** [waylaidwanderer/node-chatgpt-api#69]
Thats a great news that you have found out the way to use official models. 
Could we possibly get a the implementation for the proxy? As using someone else free proxy from github will just bring capacity sooner or later. On another side having an option for where and how your data proccessed is great.

**Comment by waylaidwanderer** [comment]
That defeats the purpose of providing a reverse proxy, as we want to keep the method private for now to hopefully avoid it being patched.

**Comment by z0lo13** [comment]
@waylaidwanderer it could be tricky with paid accounts... and anything is built with your library could be reverse enginered by looking into the prompts and responses. This said your library is suitable only for testing purposes unfortunately (I am talking about chat models)

**Comment by waylaidwanderer** [comment]
@z0lo13 The responses are transformed to look exactly like a regular response with any identifying information stripped out. I suppose it's possible that if OpenAI logs all our prompts, they can send a unique string in a prompt and find the request that way, but I don't think it's likely.

But yes, I suggest you use free accounts only if you don't trust the reverse proxy server, or stick to using `text-davinci-003`.
