### ISSUE TITLE
Reverse proxy seems down

### ISSUE THREAD

**Issue by azuretimm** [waylaidwanderer/node-chatgpt-api#71]
The reverse proxy servers worked great, but as of just now both of the two reverse proxy servers are down now, which seems inevitable given how many requests they would handle.
This happened when using cli, 2 hours ago it was working fine.
```
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:14152:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async create (file:///root/node-chatgpt-api/node_modules/@waylaidwanderer/fetch-event-source/lib/esm/fetch.js:52:34) {
  cause: Error: connect EHOSTUNREACH 2a09:8280:1::3:e03e:443
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -113,
    code: 'EHOSTUNREACH',
    syscall: 'connect',
    address: '2a09:8280:1::3:e03e',
    port: 443
  }
```

**Comment by waylaidwanderer** [comment]
We've taken down our reverse proxy servers because it seems like OpenAI patched the method we were using. We're going to investigate if there's any way to get it working again, but for now it doesn't look good :(

**Comment by waylaidwanderer** [comment]
Unfortunately, the method we used to access the ChatGPT raw models has been patched. Your options right now are to either use the official OpenAI API with the text-davinci-003 model (which costs money) or use a browser-based solution to interface with ChatGPT's backend (which is less powerful, more rate-limited, and is not supported by this library at this time).
