### ISSUE TITLE
TypeError: fetch failed

### ISSUE THREAD

**Issue by a0709** [waylaidwanderer/node-chatgpt-api#73]
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11118:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async create (file:///app/node_modules/@waylaidwanderer/fetch-event-source/lib/esm/fetch.js:52:34) {
  cause: Error: read ECONNRESET
      at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
    errno: -104,
    code: 'ECONNRESET',
    syscall: 'read'
  }
}

**Comment by a0709** [comment]
node version v18.12.1

**Comment by JerryWn12** [comment]
seems server is under DDoS attack

**Comment by a0709** [comment]
So this proxy server can't be used again?

**Comment by JerryWn12** [comment]
yes, until they stop attck

**Comment by a0709** [comment]
tkank you, Do you know how to build your own reverse proxy server?

**Comment by waylaidwanderer** [comment]
We've taken down our reverse proxy servers because it seems like OpenAI patched the method we were using. We're going to investigate if there's any way to get it working again, but for now it doesn't look good :(

**Comment by waylaidwanderer** [comment]
Closing in favor of #73

**Comment by a0709** [comment]
@waylaidwanderer still thank you

**Comment by a0709** [comment]
@waylaidwanderer Is that proxy service available now?

**Comment by asus12345AVAIALBALEELELEL** [comment]
isnt that 403 error or something like that

**Comment by asus12345AVAIALBALEELELEL** [comment]
do you know that their model is changed or no
(like in this screenshot)
![image](https://user-images.githubusercontent.com/125299786/218720268-6451a352-448c-4483-b9b5-88de0dd4ae24.png)

**Comment by waylaidwanderer** [comment]
I can't really say much right now but it seems like the method we were using is broken

**Comment by jjmpsp** [comment]
Just discovered this library and stumbled into this same error. It's a shame this method is no longer working :(

Does anyone know of any other methods to send requests to the chatgpt website and get a response? Perhaps a working implementation of something like this? https://github.com/Zeeshanahmad4/Automating-ChatGPT-with-Python-and-Selenium

**Comment by waylaidwanderer** [comment]
@jjmpsp Yeah, you'd have to use a Cloudflare bypass, but my repo doesn't support using the website to talk to ChatGPT in the first place because it was meant for the API that's coming out soon. We just got started a bit early on that, haha.
