### ISSUE TITLE
timeout for fetch

### ISSUE THREAD

**Issue by ikechan8370** [waylaidwanderer/node-chatgpt-api#74]
It seems there is no timeout option like `timeoutMs` for the function. Sometimes a request gets stuck for a long time。

**Comment by waylaidwanderer** [comment]
Do you have any examples of messages/prompts that cause this issue? Are you using `sendMessage()` and are you using `onProgress` (or `stream` with the API)?

**Comment by waylaidwanderer** [comment]
@eamd-wq if you can enable debug mode on the bing client and reproduce, that would be helpful.

**Comment by JieYueCoding** [comment]
I attach my full information. This problem occurs in some message situations.
No error occurs when asking the same question in the browser.
If the error cannot be resolved, the situation should be terminated immediately, not wait forever.
```
Type "!" to access the command menu.
? Write a message: 想拉屎厕所没坑位怎么办

⠇ Bing is typing...{
  conversationId: '51D|BingProd|D3BC4F73FFDF0753E7AD431858B85D96ACA314782AB44AE54FCE51A8040CC1AF',
  clientId: '914798183666223',
  conversationSignature: 'XWsVe/pPc7RePY52UmyvTnyE5IS27rvKmR2woRymih4=',
  result: { value: 'Success', message: null }

⠧ Bing is typing...handshake established
{"arguments":[{"source":"cib","optionsSets":["nlu_direct_response_filter","deepleo","enable_debug_commands","disable_emoji_spoken_text","responsible_ai_policy_235","enablemm"],"isStartOfSession":true,"message":{"author":"user","inputMethod":"Keyboard","text":"
想拉屎厕所没坑位怎么办","messageType":"Chat"},"conversationSignature":"XWsVe/pPc7RePY52UmyvTnyE5IS27rvKmR2woRymih4=","participant":{"id":"914798183666223"},"conversationId":"51D|BingProd|D3BC4F73FFDF0753E7AD431858B85D96ACA314782AB44AE54FCE51A8040CC1AF"}],"invoc

⠴ Bing is typing...[{"type":2,"invocationId":"0","item":{"firstNewMessageIndex":null,"suggestedResponses":null,"conversationId":"51D|BingProd|D3BC4F73FFDF0753E7AD431858B85D96ACA314782AB44AE54FCE51A8040CC1AF","requestId":"8fb54a68-87eb-4160-a0de-c991327caf45","telemetry":{"metrics":null,"startTime":"2023-02-15T06:31:34.8405486Z"},"result":{"value":"InternalError","message":"Unhandled Dependency Failure: Bing","error":"Unhandled Dependency Failure: Bing\n ---> ServiceClient failure for Bing","exception":"Microsoft.TuringBot.Common.ServiceInternalError: Unhandled Dependency Failure: Bing\r\n ---> Microsoft.TuringBot.Common.ServiceClientException: ServiceClient failure for Bing\r\n ---> System.Net.Http.HttpRequestException: Failed to call \"Bing\" at \"https://www.bing.com/api/v7/search?appid=[REDACTED]&q=%e6%83%b3%e6%8b%89%e5%b1%8e%e5%8e%95%e6%89%80%e6%b2%a1%e5%9d%91%e4%bd%8d%e6%80%8e%e4%b9%88%e5%8a%9e&format=json&conversation=true&screenshotstyle=small&setLang=en-us&mkt=en-us\". StatusCode=Redirect - ReasonPhrase=Found.\r\n   
at BotClientLibrary.ServiceClients.ServiceClient.SendHttpRequest(String url, HttpRequestMessage request, TelemetryScope scope, CancellationToken cancellationToken, String serviceName, ServiceClientOptions options) in C:\\a\\_work\\1\\s\\services\\TuringBot\\src\\BotClientLibrary\\ServiceClients\\ServiceClient.cs:line 549\r\n   at BotClientLibrary.ServiceClients.ServiceClient.Run(Conversation conversation, Message message, CancellationToken cancellationToken, BatchRequest batchRequest, ServiceClientOptions options) in C:\\a\\_work\\1\\s\\services\\TuringBot\\src\\BotClientLibrary\\ServiceClients\\ServiceClient.cs:line 354\r\n   --- End of inner exception stack trace ---\r\n   at BotClientLibrary.ServiceClients.PassageFinder.PassageFinder.Run(Conversation conversation, Message message, CancellationToken cancellationToken) in C:\\a\\_work\\1\\s\\services\\TuringBot\\src\\BotClientLibrary\\ServiceClients\\PassageFinder\\PassageFinder.cs:line 138\r\n   at BotClientLibrary.Extensions.DeepLeoOrchestrator.DoWebSearch(ExtensionResponse result, Conversation conversation, Message searchQueryMessage, DeepLeoConfiguration config, Dictionary`2 searchResultScenarioMapping, DeepLeoMessageFactory messageFactory, IEnumerable`1 searchResultFilters, RenderCardMessageFilter renderCardFilter, CancellationToken cancellationToken) in C:\\a\\_work\\1\\s\\services\\TuringBot\\src\\BotClientLibrary\\Extensions\\DeepLeoOrchestrator.cs:line 539\r\n   at BotClientLibrary.Extensions.DeepLeoOrchestrator.RunDeepLeoEngine(ExtensionResponse result, Conversation conversation, TuringBotConfiguration config, Message message, DeepLeoMessageFactory messageFactory) in C:\\a\\_work\\1\\s\\services\\TuringBot\\src\\BotClientLibrary\\Extensions\\DeepLeoOrchestrator.cs:line 412\r\n   at BotClientLibrary.Extensions.DeepLeoOrchestrator.Run(Exbrary\\Extensions\\ExtensionRunner.cs:line 375\r\n   at BotClientLibrary.Extensions.ExtensionRunner.RunExtensions(Conversation conversation, CancellationToken cancellationToken, ComponentPriority minPriority, ComposionRunner.RunExtension(Conversation conversatinentPriority maxPriority, ExtensionRequestOptions customOptions) in C:\\a\\_work\\1\\s\\services\\TuringBot\\src\\BotClientLibrary\\Extensions\\ExtensionRunner.cs:line 99\r\n   at BotClientLibrary.ServiceClients.Orr\n   at BotClientLibrary.Extensions.ExtensionRchestrator.PreOrchestrate(Conversation conversation, CancellationToken cancellationToken) in C:\\a\\_work\\1\\s\\services\\TuringBot\\src\\BotClientLibrary\\ServiceClients\\Orchestrator.cs:line 568\r\n   at BotCliees\\TuringBot\\src\\BotClientLibrary\\ExtensionntLibrary.BotConnection.InternalRun(Conversation conversation, CancellationToken cancellationToken) in C:\\a\\_work\\1\\s\\services\\TuringBot\\src\\BotClientLibrary\\BotConnection.cs:line 638\r\n   at BotClientLibtClientLibrary\\ServiceClients\\Orchestrator.csrary.BotConnection.ExecuteBotTurn(Conversation conversation, CancellationToken cancellationToken) in C:\\a\\_work\\1\\s\\services\\TuringBot\\src\\BotClientLibrary\\BotConnection.cs:line 396\r\n   --- End of inner  638\r\n   at BotClientLibrary.BotConnection.Ex
exception stack trace ---\r\n   at BotClientLibrary.BotConnection.ExecuteBotTurn(Conversation conversation, CancellationToken cancellationToken) in C:\\a\\_work\\1\\s\\services\\TuringBot\\src\\BotClientLibrary\\Bo ---\r\n   at BotClientLibrary.BotConnection.ExtConnection.cs:line 396\r\n   at BotClientLibrary.BotConnection.ExecuteBotTurn(Conversation conversation, CancellationToken cancellationToken) in C:\\a\\_work\\1\\s\\services\\TuringBot\\src\\BotClientLibrary\\BotCuteBotTurn(Conversation conversation, Cancellatonnection.cs:line 396\r\n   at BotClientLibrary.BotConnection.Run(CancellationToken cancellationToken) in C:\\a\\_work\\1\\s\\services\\TuringBot\\src\\BotClientLibrary\\BotConnection.cs:line 136\r\n   at Microsoftork\\1\\s\\services\\TuringBot\\src\\BotClientL.Falcon.TuringBot.ChatApiImplementation.Run(BaseRequest request, BaseResponse response, CancellationToken cancellationToken) in C:\\a\\_work\\1\\s\\services\\TuringBot\\src\\Service\\Implementation\\ApiImplementatingBot\\src\\Service\\Implementation\\ApiImplemeon\\ChatApiImplementation.cs:line 88\r\n   at Microsoft.Falcon.TuringBot.RequestProcessor.Run(BaseRequest request, BaseResponse response, IRequestContextInitializer contextInitializer, IRequestValidator requestValitValidator, IApiImplementation apiImplementatiodator, IApiImplementation apiImplementatio

⠋ Bing is typing...
```

**Comment by ikechan8370** [comment]
> I attach my full information. This problem occurs in some message situations. No error occurs when asking the same question in the browser. If the error cannot be resolved, the situation should be terminated immediately, not wait forever.
> 
> ```
> Type "!" to access the command menu.
> ? Write a message: 想拉屎厕所没坑位怎么办
> 
> ⠇ Bing is typing...{
>   conversationId: '51D|BingProd|D3BC4F73FFDF0753E7AD431858B85D96ACA314782AB44AE54FCE51A8040CC1AF',
>   clientId: '914798183666223',
>   conversationSignature: 'XWsVe/pPc7RePY52UmyvTnyE5IS27rvKmR2woRymih4=',
>   result: { value: 'Success', message: null }
> 
> ⠧ Bing is typing...handshake established
> {"arguments":[{"source":"cib","optionsSets":["nlu_direct_response_filter","deepleo","enable_debug_commands","disable_emoji_spoken_text","responsible_ai_policy_235","enablemm"],"isStartOfSession":true,"message":{"author":"user","inputMethod":"Keyboard","text":"
> 想拉屎厕所没坑位怎么办","messageType":"Chat"},"conversationSignature":"XWsVe/pPc7RePY52UmyvTnyE5IS27rvKmR2woRymih4=","participant":{"id":"914798183666223"},"conversationId":"51D|BingProd|D3BC4F73FFDF0753E7AD431858B85D96ACA314782AB44AE54FCE51A8040CC1AF"}],"invoc
> 
> ⠴ Bing is typing...[{"type":2,"invocationId":"0","item":{"firstNewMessageIndex":null,"suggestedResponses":null,"conversationId":"51D|BingProd|D3BC4F73FFDF0753E7AD431858B85D96ACA314782AB44AE54FCE51A8040CC1AF","requestId":"8fb54a68-87eb-4160-a0de-c991327caf45","telemetry":{"metrics":null,"startTime":"2023-02-15T06:31:34.8405486Z"},"result":{"value":"InternalError","message":"Unhandled Dependency Failure: Bing","error":"Unhandled Dependency Failure: Bing\n ---> ServiceClient failure for Bing","exception":"Microsoft.TuringBot.Common.ServiceInternalError: Unhandled Dependency Failure: Bing\r\n ---> Microsoft.TuringBot.Common.ServiceClientException: ServiceClient failure for Bing\r\n ---> System.Net.Http.HttpRequestException: Failed to call \"Bing\" at \"https://www.bing.com/api/v7/search?appid=[REDACTED]&q=%e6%83%b3%e6%8b%89%e5%b1%8e%e5%8e%95%e6%89%80%e6%b2%a1%e5%9d%91%e4%bd%8d%e6%80%8e%e4%b9%88%e5%8a%9e&format=json&conversation=true&screenshotstyle=small&setLang=en-us&mkt=en-us\". StatusCode=Redirect - ReasonPhrase=Found.\r\n   
> at BotClientLibrary.ServiceClients.ServiceClient.SendHttpRequest(String url, HttpRequestMessage request, TelemetryScope scope, CancellationToken cancellationToken, String serviceName, ServiceClientOptions options) in C:\\a\\_work\\1\\s\\services\\TuringBot\\src\\BotClientLibrary\\ServiceClients\\ServiceClient.cs:line 549\r\n   at BotClientLibrary.ServiceClients.ServiceClient.Run(Conversation conversation, Message message, CancellationToken cancellationToken, BatchRequest batchRequest, ServiceClientOptions options) in C:\\a\\_work\\1\\s\\services\\TuringBot\\src\\BotClientLibrary\\ServiceClients\\ServiceClient.cs:line 354\r\n   --- End of inner exception stack trace ---\r\n   at BotClientLibrary.ServiceClients.PassageFinder.PassageFinder.Run(Conversation conversation, Message message, CancellationToken cancellationToken) in C:\\a\\_work\\1\\s\\services\\TuringBot\\src\\BotClientLibrary\\ServiceClients\\PassageFinder\\PassageFinder.cs:line 138\r\n   at BotClientLibrary.Extensions.DeepLeoOrchestrator.DoWebSearch(ExtensionResponse result, Conversation conversation, Message searchQueryMessage, DeepLeoConfiguration config, Dictionary`2 searchResultScenarioMapping, DeepLeoMessageFactory messageFactory, IEnumerable`1 searchResultFilters, RenderCardMessageFilter renderCardFilter, CancellationToken cancellationToken) in C:\\a\\_work\\1\\s\\services\\TuringBot\\src\\BotClientLibrary\\Extensions\\DeepLeoOrchestrator.cs:line 539\r\n   at BotClientLibrary.Extensions.DeepLeoOrchestrator.RunDeepLeoEngine(ExtensionResponse result, Conversation conversation, TuringBotConfiguration config, Message message, DeepLeoMessageFactory messageFactory) in C:\\a\\_work\\1\\s\\services\\TuringBot\\src\\BotClientLibrary\\Extensions\\DeepLeoOrchestrator.cs:line 412\r\n   at BotClientLibrary.Extensions.DeepLeoOrchestrator.Run(Exbrary\\Extensions\\ExtensionRunner.cs:line 375\r\n   at BotClientLibrary.Extensions.ExtensionRunner.RunExtensions(Conversation conversation, CancellationToken cancellationToken, ComponentPriority minPriority, ComposionRunner.RunExtension(Conversation conversatinentPriority maxPriority, ExtensionRequestOptions customOptions) in C:\\a\\_work\\1\\s\\services\\TuringBot\\src\\BotClientLibrary\\Extensions\\ExtensionRunner.cs:line 99\r\n   at BotClientLibrary.ServiceClients.Orr\n   at BotClientLibrary.Extensions.ExtensionRchestrator.PreOrchestrate(Conversation conversation, CancellationToken cancellationToken) in C:\\a\\_work\\1\\s\\services\\TuringBot\\src\\BotClientLibrary\\ServiceClients\\Orchestrator.cs:line 568\r\n   at BotCliees\\TuringBot\\src\\BotClientLibrary\\ExtensionntLibrary.BotConnection.InternalRun(Conversation conversation, CancellationToken cancellationToken) in C:\\a\\_work\\1\\s\\services\\TuringBot\\src\\BotClientLibrary\\BotConnection.cs:line 638\r\n   at BotClientLibtClientLibrary\\ServiceClients\\Orchestrator.csrary.BotConnection.ExecuteBotTurn(Conversation conversation, CancellationToken cancellationToken) in C:\\a\\_work\\1\\s\\services\\TuringBot\\src\\BotClientLibrary\\BotConnection.cs:line 396\r\n   --- End of inner  638\r\n   at BotClientLibrary.BotConnection.Ex
> exception stack trace ---\r\n   at BotClientLibrary.BotConnection.ExecuteBotTurn(Conversation conversation, CancellationToken cancellationToken) in C:\\a\\_work\\1\\s\\services\\TuringBot\\src\\BotClientLibrary\\Bo ---\r\n   at BotClientLibrary.BotConnection.ExtConnection.cs:line 396\r\n   at BotClientLibrary.BotConnection.ExecuteBotTurn(Conversation conversation, CancellationToken cancellationToken) in C:\\a\\_work\\1\\s\\services\\TuringBot\\src\\BotClientLibrary\\BotCuteBotTurn(Conversation conversation, Cancellatonnection.cs:line 396\r\n   at BotClientLibrary.BotConnection.Run(CancellationToken cancellationToken) in C:\\a\\_work\\1\\s\\services\\TuringBot\\src\\BotClientLibrary\\BotConnection.cs:line 136\r\n   at Microsoftork\\1\\s\\services\\TuringBot\\src\\BotClientL.Falcon.TuringBot.ChatApiImplementation.Run(BaseRequest request, BaseResponse response, CancellationToken cancellationToken) in C:\\a\\_work\\1\\s\\services\\TuringBot\\src\\Service\\Implementation\\ApiImplementatingBot\\src\\Service\\Implementation\\ApiImplemeon\\ChatApiImplementation.cs:line 88\r\n   at Microsoft.Falcon.TuringBot.RequestProcessor.Run(BaseRequest request, BaseResponse response, IRequestContextInitializer contextInitializer, IRequestValidator requestValitValidator, IApiImplementation apiImplementatiodator, IApiImplementation apiImplementatio
> 
> ⠋ Bing is typing...
> ```

I use the p-timeout package to temporarily solve this problem.

**Comment by waylaidwanderer** [comment]
Hi, please update to `1.16.2` which fixes this issue.

**Comment by waylaidwanderer** [comment]
Sorry, not 1.16.2, 1.16.3.

**Comment by waylaidwanderer** [comment]
Pushed another patch that detects errors better, 1.16.4.
