### ISSUE TITLE
Unauthorized - Access token is missing

### ISSUE THREAD

**Issue by danielmaela04** [waylaidwanderer/node-chatgpt-api#76]
I tried to access the website _**https://chat.openai.com/backend-api/models**_, but I received an authorization error message that said: '_Unauthorized - Access token is missing_': 
`{
"detail": {
"message": "Unauthorized - Access token is missing"
}
}`

**how can i solve this??**

_**thanks in advance**_

**Comment by waylaidwanderer** [comment]
You're not supposed to access it directly, which is why the instructions say to inspect the network request after refreshing.

However, the reverse proxy method isn't working right now.
