### ISSUE TITLE
getting error when using or not using reverse proxy

### ISSUE THREAD

**Issue by rl3250** [waylaidwanderer/node-chatgpt-api#77]
I keep getting

`  cause: Error: read ECONNRESET
      at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
    errno: -54,
    code: 'ECONNRESET',
    syscall: 'read'
  },
  page: '/api/infra/service'
}`
error when using the latest version. I tried both not using reverse proxy and using reverse proxy

**Comment by waylaidwanderer** [comment]
The reverse proxy isn't working right now. Is it working if you use the API key and `text-davinci-003`?
