### ISSUE TITLE
Error: UnauthorizedRequest: Sorry, you are not allowed to access this service

### ISSUE THREAD

**Issue by cherish6092** [waylaidwanderer/node-chatgpt-api#79]
the cookie value of bing.com doesn't work out

**Comment by waylaidwanderer** [comment]
Do you have a cookie named `KievRPSSecAuth`?

**Comment by waylaidwanderer** [comment]
@AuYuHui Instead of setting
```JS
userToken: '<value>'
```
set
```JS
cookies: 'KievRPSSecAuth=<value>'
```
instead.

**Comment by waylaidwanderer** [comment]
Oh, and please update to `1.16.5` first.

**Comment by cherish6092** [comment]
i don't have KievRPSSecAuth

**Comment by AuYuHui** [comment]
I set all cookies, the same error

**Comment by waylaidwanderer** [comment]
@cherish6092 Make sure you actually have access to Bing Chat and that you're not still on the waitlist.

@AuYuHui can you show me a screenshot of your settings? Make sure to redact any information like the actual values of the cookies, but I want to see how you set them.

**Comment by AuYuHui** [comment]
![微信截图_20230215173312](https://user-images.githubusercontent.com/38815121/218989659-22573dc1-5e6a-4c34-b465-2e9fb81b53a3.png)



`_EDGE_V=1; USRLOC=HS=1&CLOC=LAT=23.0608154119852|LON=113.30398545826036|A=733.4464586120832|TS=230215060650|SRC=W; SRCHD=AF=NOFORM; SRCHUID=V=2&GUID=C012727425A34EBCA1CEC47B15333FF9&dmnchg=1; _UR=QS=0&TQS=0; MicrosoftApplicationsTelemetryDeviceId=878dd5d0-6d67-4007-b4f2-b61157ff59f5; _HPVN=CS=eyJQbiI6eyJDbiI6MSwiU3QiOjAsIlFzIjowLCJQcm9kIjoiUCJ9LCJTYyI6eyJDbiI6MSwiU3QiOjAsIlFzIjowLCJQcm9kIjoiSCJ9LCJReiI6eyJDbiI6MSwiU3QiOjAsIlFzIjowLCJQcm9kIjoiVCJ9LCJBcCI6dHJ1ZSwiTXV0ZSI6dHJ1ZSwiTGFkIjoiMjAyMy0wMi0xNVQwMDowMDowMFoiLCJJb3RkIjowLCJHd2IiOjAsIkRmdCI6bnVsbCwiTXZzIjowLCJGbHQiOjAsIkltcCI6Mn0=; ipv6=hit=1676455031709&t=4; MUID=2646225797F6675D113D304896BC6638; NAP=V=1.9&E=1ba3&C=8MSeGABW74l2NpRvSzI51v-TTz5c_10BO2w63kdmhfDXmYTSA66rnw&W=1; PPLState=1; KievRPSSecAuth=FABSBBRaTOJILtFsMkpLVWSG6AN6C/svRwNmAAAEgAAACCqjGA5bGzEwEASBHgZTwDNNme4givCqaE6Bg1A9KfD+9OEY8n+qon3a9lbKmPo4FGbpvZir/Ro1OR5QS1hANT1kWl4NhnUfZpH/XitYrsYLjqRT2lbJtSJOm1lBgjPbq6zwyLI/p9XYRtNn9nDMC3gR5U3fdZZbjWYalv3POvINw0j6nLtq8z/gNq9f1aSoErBwVUrcod4zjjKgRn7nQk5DcahXQniRlgDPWKxKQ97NXYlkJxH4coUF6SoHCzSLqqbtceXbFJOz7r7nxZU1RraJpB22j7SYZg6auOU2u50Rn0e8KMhNTnbXReipOluJW9dCetZHeK81XPji01XOGrRAlO8GE3bSLd6bnW9VMYuMEByyN1fz9yzMc5AoVQs87K/Yn703QbAOuh6fX4eTAIakR0JLEKChXUF0xdbAp/C02fGQC0znUZR9qjqZ9qVH5PB//JRgE/MxJ9iV7ej/RCzrfp6rKYiaPsNOznJe7a0tREGiBRhZSiA0NEgSzJ2Jp9nkaPFrkNIfWLlbmHGZNJaOaIlLSGrylVZZDJxZBLbwYcgRGhg1eU5euUDa98330mYjHX06IqzP4HMjfN8vx0pwfBfEvsQK4otvWd3z2ZeFBYesMoptAgmRGO9sInWufVSFv5Tgt0XLS4Cir7yF/l7Y/n3MzK3ImAHtiRAR1n7HoHnPDLNxlaZjuU7jtU/z1hxbBnnswY3Ro90gf/m0W8fgLu8SlkLOkGO7Zh+IGtUXqfLddrZxD3kgIF97r5Q9MV7NKtnRwsEWBQ7u/Ugv3TRU/EB/kZ/ukJZ6rhG5JP4dYalhrS7QFRtAVd9ov1Pqcdof2QZtavnjEaMBFk0PWG/gSY8Z1d33w2rD1Q+iKDru5A23hUeI93+TEC/To+AVX9F0daqgh4Zh53kdDCZhIfcfnpxmm0YUQl2xVIv44OTnLPgwsPL4RMiNf/2mkN9i8xMa46LFTW3MozoJGKiR21NU5ATMFOsmRbGdgGgKLwb7yRUbm4LaRSyRrm02LURupvZ4NjpZHO0VNveF2fxKVV89hedfKczfDoa/jwUGC8FFettgGGbrzups+lSYKNmR3TJyfXFzqI0mzkkLOSrQS/PvJR+NGvBCJdkiKXurGcbsNViFyAU+IyHARmtcJDNYl5YfQYKlZaKSaBtdszV2jWbyW1n+oniBDlRogz990t9CCMdIoCL0nQMw07E5iw43T8+fgIC5m4PCTY4b/v1wEKsIt+jI+7c5STs6Pm255LUJJxO41Cec+Gp4EInsyQuSBBj407iZHFfFIQt40Vcmj4AmwJGHM1OZpfoKqgpilmI26sguYOKyj346PpUfRMQbyBqYCbYGwG5MQ4qdiV6R3Neao5ErCmojpNobT6jYzD9e1PBVl4MyQOSOcxQAuzNGQMlDhsUncxWDAVrZu594FrE=; SRCHUSR=DOB=20230215&T=1676451427000&POEX=W; WLID=aQX/0qWGFqbN014suoaeHBKtPg4PwlThy1/S1CgIhMLi5ievDFdzDmSdzQtAoRBCG0ziQrKKNx6aZRC0MIK3ZGBCdPSNaWSprmWEB8eOVFU=; SUID=A; MUIDB=2646225797F6675D113D304896BC6638; SnrOvr=X=rebateson; dsc=order=ShopOrderDefault; _SS=SID=15E5C29BEEEA6C7036BBD022EF596D7C&R=222&RB=222&GB=0&RG=0&RP=222&PC=EE09; SRCHS=PC=EE09; ZHCHATSTRONGATTRACT=TRUE; ZHCHATWEAKATTRACT=TRUE; _U=1I7kFujTSSMr1UkXVMLKwK_Vv8-WwyGSzBdPKiAFjedlpn6K1COMzbuMVWct27l8z8cWKjK_iMH3GHA99v2r7_RR2gs5Pb-ASw0R3tuP7PhqJTm7Nuu3OWoOg9vSREv3YVPaEysWwLHjsJU97V6BpUFRJRo20tHA6v5CENjGxPgFiwmvJ0eWHmqk61bIVeDgP6_TTGgFe2MICcYu4Ns_JpQ; ANON=A=980540CE233B7185FD98D1FFFFFFFFFF&E=1bfd&W=1; WLS=C=786d136133929b28&N=yuhui; _RwBf=ilt=1&ihpd=1&ispd=0&rc=222&rb=222&gb=0&rg=0&pc=222&mtu=0&rbb=0.0&g=0&cid=&clo=0&v=6&l=2023-02-15T08:00:00.0000000Z&lft=0001-01-01T00:00:00.0000000&aof=0&o=0&p=bingcopilotwaitlist&c=MY00IA&t=1246&s=2023-02-08T03:25:59.7759955+00:00&ts=2023-02-15T09:06:02.4991579+00:00&rwred=0&wls=2&lka=0&lkt=0&TH=&r=1&mta=0&e=2FUE7cGcAHwb3uFqB1TrsUQxir2J6GvDtRlzoLcM7nRffd4yEgyDn5jfd2J_iB3as98KeQ7ZbX4EOkjc4ObW9g&A=D37723220A3CB3BB8D9D8508FFFFFFFF; _EDGE_S=F=1&SID=15E5C29BEEEA6C7036BBD022EF596D7C&mkt=zh-cn; SRCHHPGUSR=SRCHLANG=zh-Hans&PV=10.0.0&BRW=N&BRH=M&CW=1213&CH=937&SCW=1402&SCH=1553&DPR=1.0&UTC=480&DM=0&PRVCW=1920&PRVCH=937&EXLTT=5&HV=1676451965&BZA=0`

**Comment by waylaidwanderer** [comment]
@AuYuHui I'm not sure what the issue is, then. It's working correctly for me. To confirm, do you have access to Bing Chat already?

(Also you should probably log out of that session because you sent your cookies here and anyone with those cookies can login as you.)

**Comment by AuYuHui** [comment]
I can chat

**Comment by waylaidwanderer** [comment]
Unfortunately I don't think I can figure out the issue without having access to your account :(

**Comment by waylaidwanderer** [comment]
@AuYuHui I think I figured out the issue, please try it again

**Comment by waylaidwanderer** [comment]
@cherish6092 I think this may have fixed your issue too btw

**Comment by AuYuHui** [comment]
Use BingAIClient alone to report errors， I try to use the API Server and can respond

![image](https://user-images.githubusercontent.com/38815121/219260200-d07a2174-98a9-45d6-9fe3-39baa802f8ff.png)

**Comment by waylaidwanderer** [comment]
So it's working?

**Comment by AuYuHui** [comment]
yes

**Comment by eu09** [comment]
Could u let me know where I can find the cookie ?

**Comment by waylaidwanderer** [comment]
You can copy it easily by opening Dev Tools, looking at a Fetch/XHR request, and then copying the Cookie value under "Request Headers".

![image](https://user-images.githubusercontent.com/2882110/219617272-a693502c-5117-4818-8986-b4569211466b.png)
