### ISSUE TITLE
That model does not exist

### ISSUE THREAD

**Issue by DockerChen** [waylaidwanderer/node-chatgpt-api#80]
when run chatgpt cli, the program error:"That model does not exist"

**Comment by waylaidwanderer** [comment]
Unfortunately, the method we were using to access the ChatGPT raw models has been patched. Your options right now are to either use the official OpenAI API with the text-davinci-003 model (which costs money) or use a browser-based solution to interface with ChatGPT's backend (which is less powerful, more rate-limited, and is not supported by this library at this time).
