### ISSUE TITLE
"error": "There was an error communicating with Bing."

### ISSUE THREAD

**Issue by CherryPeel** [waylaidwanderer/node-chatgpt-api#82]
同样的一个msg，用中文就是报错，用英文反而可以正常响应，这是因为啥？

The same msg report errors in Chinese but can respond normally in English. Why?

![image](https://user-images.githubusercontent.com/48341841/219109041-66179265-b370-46bb-b8c2-e783007873a2.png)

English:
![image](https://user-images.githubusercontent.com/48341841/219109326-04b4ebda-e94e-4d23-a3d9-8242ad6ded07.png)

**Comment by waylaidwanderer** [comment]
@CherryPeel It's working for me. Please update to the latest version of the package and try again. Let me know if it works!
![image](https://user-images.githubusercontent.com/2882110/219228569-aeec3deb-3000-44bf-924d-6cc454522e7f.png)
