### ISSUE TITLE
Both browser and local code won't work

### ISSUE THREAD

**Issue by KevinKaiwenZheng** [waylaidwanderer/node-chatgpt-api#89]
I cannot access my Bing after using the reverse-engineered API, and the API doesn't work with my cookies as well, saying that it is not authorized. The browser end wouldn't work either. Does anyone else has the same problem?

**Comment by waylaidwanderer** [comment]
Yes, it's a known issue, see this thread: https://www.reddit.com/r/bing/comments/1146zd6/bing_ai_constantly_attempting_to_reconnect

**Comment by KevinKaiwenZheng** [comment]
My Bing is saying "Somthing went wrong" with a circle spinning and a refresh button. Not entirely reconnecting I think.

**Comment by waylaidwanderer** [comment]
That one is also happening to other people too.

**Comment by KevinKaiwenZheng** [comment]
Yup, found a post on reddit https://www.reddit.com/r/bing/comments/114al04/is_the_new_bing_down_or_is_it_just_to_me/
I'll be updating here if the service is back on.

**Comment by eu09** [comment]
New Censor from freedom country. Coool

**Comment by KevinKaiwenZheng** [comment]
The new Bing is back online, but Sydney's gone...f**k microsoft
