### ISSUE TITLE
Conversation Expired

### ISSUE THREAD

**Issue by everplus** [waylaidwanderer/node-chatgpt-api#90]
[{"type":2,"invocationId":"11","item":{"firstNewMessageIndex":null,"suggestedResponses":null,"conversationId":"xxxxxx","requestId":"xxxxxx","telemetry":{"metrics":null,"startTime":"2023-02-17T08:22:07.5418739Z"},"result":{"value":"InvalidSession","message":"Conversation 'xxxxxx' doesn't exist or has expired. Conversations expire after 06:00:00 minutes.","serviceVersion":"20230216.117"}}},{"type":3,"invocationId":"11"}]

The sendMessage will never return

**Comment by waylaidwanderer** [comment]
Thanks. PR is welcome or I will get around to fixing it later.
