### ISSUE TITLE
there are some things wrong

### ISSUE THREAD

**Issue by pfeducode** [waylaidwanderer/node-chatgpt-api#93]
![image](https://user-images.githubusercontent.com/100210045/219853879-2ffce921-7917-4507-85e8-b5891e4607f7.png)
![image](https://user-images.githubusercontent.com/100210045/219853947-ece63448-0cd4-4885-958f-309936ad52cb.png)

**Comment by wjason** [comment]
the same. it display 404

**Comment by waylaidwanderer** [comment]
As per the readme, we no longer have access to ChatGPT raw models until the API is officially available. You can use text-davinci-003 in the meantime.

**Comment by opticalix** [comment]
> 

how to switch to davinci-003 with the OPEN_AI_KEY?

**Comment by opticalix** [comment]
> As per the readme, we no longer have access to ChatGPT raw models until the API is officially available. You can use text-davinci-003 in the meantime.

how to switch to davinci-003 with the OPEN_AI_KEY?
