### ISSUE TITLE
My bing is not working, prompt Throttled: Request is throttled

### ISSUE THREAD

**Issue by eamd-wq** [waylaidwanderer/node-chatgpt-api#96]
My bing is not working, prompt Throttled: Request is throttled，There was no change in my code, and I also tried to change the token. I guess bing.com modified some configurations

**Comment by waylaidwanderer** [comment]
They've added a limit of 5 turns per conversation and 50 conversation turns per day, last I heard. One "turn" is 1 user and 1 bot message.
