### ISSUE TITLE
tokens

### ISSUE THREAD

**Issue by Kucklovod00** [waylaidwanderer/node-chatgpt-api#97]
Hello

tell me how can I limit the number of tokens?

Users run out of funds very quickly

**Comment by waylaidwanderer** [comment]
That's not possible right now, but it's a good idea for a feature/config to limit the max tokens per prompt.

**Comment by Kucklovod00** [comment]
please do it.  much needed feature

**Comment by waylaidwanderer** [comment]
Implemented in https://github.com/waylaidwanderer/node-chatgpt-api/releases/tag/v1.20.0
